// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: econ_gcmessages.proto

#include "econ_gcmessages.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR CMsgGCGiftedItems::CMsgGCGiftedItems(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.recipients_accountids_)*/{}
  , /*decltype(_impl_.accountid_)*/0u
  , /*decltype(_impl_.giftdefindex_)*/0u
  , /*decltype(_impl_.max_gifts_possible_)*/0u
  , /*decltype(_impl_.num_eligible_recipients_)*/0u} {}
struct CMsgGCGiftedItemsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgGCGiftedItemsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCGiftedItemsDefaultTypeInternal() {}
  union {
    CMsgGCGiftedItems _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCGiftedItemsDefaultTypeInternal _CMsgGCGiftedItems_default_instance_;
PROTOBUF_CONSTEXPR CMsgApplyAutograph::CMsgApplyAutograph(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.autograph_item_id_)*/uint64_t{0u}
  , /*decltype(_impl_.item_item_id_)*/uint64_t{0u}} {}
struct CMsgApplyAutographDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgApplyAutographDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgApplyAutographDefaultTypeInternal() {}
  union {
    CMsgApplyAutograph _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgApplyAutographDefaultTypeInternal _CMsgApplyAutograph_default_instance_;
PROTOBUF_CONSTEXPR CMsgGCUserTrackTimePlayedConsecutively::CMsgGCUserTrackTimePlayedConsecutively(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.state_)*/0u} {}
struct CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal() {}
  union {
    CMsgGCUserTrackTimePlayedConsecutively _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal _CMsgGCUserTrackTimePlayedConsecutively_default_instance_;
static ::_pb::Metadata file_level_metadata_econ_5fgcmessages_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_econ_5fgcmessages_2eproto[3];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_econ_5fgcmessages_2eproto = nullptr;

const uint32_t TableStruct_econ_5fgcmessages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_.accountid_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_.giftdefindex_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_.max_gifts_possible_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_.num_eligible_recipients_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_.recipients_accountids_),
  0,
  1,
  2,
  3,
  ~0u,
  PROTOBUF_FIELD_OFFSET(::CMsgApplyAutograph, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgApplyAutograph, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgApplyAutograph, _impl_.autograph_item_id_),
  PROTOBUF_FIELD_OFFSET(::CMsgApplyAutograph, _impl_.item_item_id_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::CMsgGCUserTrackTimePlayedConsecutively, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCUserTrackTimePlayedConsecutively, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgGCUserTrackTimePlayedConsecutively, _impl_.state_),
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, -1, sizeof(::CMsgGCGiftedItems)},
  { 16, 24, -1, sizeof(::CMsgApplyAutograph)},
  { 26, 33, -1, sizeof(::CMsgGCUserTrackTimePlayedConsecutively)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_CMsgGCGiftedItems_default_instance_._instance,
  &::_CMsgApplyAutograph_default_instance_._instance,
  &::_CMsgGCUserTrackTimePlayedConsecutively_default_instance_._instance,
};

const char descriptor_table_protodef_econ_5fgcmessages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025econ_gcmessages.proto\032\023steammessages.p"
  "roto\"\230\001\n\021CMsgGCGiftedItems\022\021\n\taccountid\030"
  "\001 \001(\r\022\024\n\014giftdefindex\030\002 \001(\r\022\032\n\022max_gifts"
  "_possible\030\003 \001(\r\022\037\n\027num_eligible_recipien"
  "ts\030\004 \001(\r\022\035\n\025recipients_accountids\030\005 \003(\r\""
  "E\n\022CMsgApplyAutograph\022\031\n\021autograph_item_"
  "id\030\001 \001(\004\022\024\n\014item_item_id\030\002 \001(\004\"7\n&CMsgGC"
  "UserTrackTimePlayedConsecutively\022\r\n\005stat"
  "e\030\001 \001(\r*\203&\n\nEGCItemMsg\022\021\n\014k_EMsgGCBase\020\350"
  "\007\022\034\n\027k_EMsgGCSetItemPosition\020\351\007\022\022\n\rk_EMs"
  "gGCCraft\020\352\007\022\032\n\025k_EMsgGCCraftResponse\020\353\007\022"
  "\023\n\016k_EMsgGCDelete\020\354\007\022$\n\037k_EMsgGCVerifyCa"
  "cheSubscription\020\355\007\022\025\n\020k_EMsgGCNameItem\020\356"
  "\007\022\030\n\023k_EMsgGCUnlockCrate\020\357\007\022 \n\033k_EMsgGCU"
  "nlockCrateResponse\020\360\007\022\026\n\021k_EMsgGCPaintIt"
  "em\020\361\007\022\036\n\031k_EMsgGCPaintItemResponse\020\362\007\022\"\n"
  "\035k_EMsgGCGoldenWrenchBroadcast\020\363\007\022\030\n\023k_E"
  "MsgGCMOTDRequest\020\364\007\022 \n\033k_EMsgGCMOTDReque"
  "stResponse\020\365\007\022\'\n\"k_EMsgGCAddItemToSocket"
  "_DEPRECATED\020\366\007\022/\n*k_EMsgGCAddItemToSocke"
  "tResponse_DEPRECATED\020\367\007\022+\n&k_EMsgGCAddSo"
  "cketToBaseItem_DEPRECATED\020\370\007\022\'\n\"k_EMsgGC"
  "AddSocketToItem_DEPRECATED\020\371\007\022/\n*k_EMsgG"
  "CAddSocketToItemResponse_DEPRECATED\020\372\007\022\031"
  "\n\024k_EMsgGCNameBaseItem\020\373\007\022!\n\034k_EMsgGCNam"
  "eBaseItemResponse\020\374\007\022(\n#k_EMsgGCRemoveSo"
  "cketItem_DEPRECATED\020\375\007\0220\n+k_EMsgGCRemove"
  "SocketItemResponse_DEPRECATED\020\376\007\022!\n\034k_EM"
  "sgGCCustomizeItemTexture\020\377\007\022)\n$k_EMsgGCC"
  "ustomizeItemTextureResponse\020\200\010\022\033\n\026k_EMsg"
  "GCUseItemRequest\020\201\010\022\034\n\027k_EMsgGCUseItemRe"
  "sponse\020\202\010\022#\n\036k_EMsgGCGiftedItems_DEPRECA"
  "TED\020\203\010\022\033\n\026k_EMsgGCRemoveItemName\020\206\010\022\034\n\027k"
  "_EMsgGCRemoveItemPaint\020\207\010\022\031\n\024k_EMsgGCGif"
  "tWrapItem\020\210\010\022!\n\034k_EMsgGCGiftWrapItemResp"
  "onse\020\211\010\022\030\n\023k_EMsgGCDeliverGift\020\212\010\022%\n k_E"
  "MsgGCDeliverGiftResponseGiver\020\213\010\022(\n#k_EM"
  "sgGCDeliverGiftResponseReceiver\020\214\010\022\036\n\031k_"
  "EMsgGCUnwrapGiftRequest\020\215\010\022\037\n\032k_EMsgGCUn"
  "wrapGiftResponse\020\216\010\022\031\n\024k_EMsgGCSetItemSt"
  "yle\020\217\010\022\036\n\031k_EMsgGCUsedClaimCodeItem\020\220\010\022\026"
  "\n\021k_EMsgGCSortItems\020\221\010\022*\n%k_EMsgGC_Revol"
  "vingLootList_DEPRECATED\020\222\010\022\032\n\025k_EMsgGCLo"
  "okupAccount\020\223\010\022\"\n\035k_EMsgGCLookupAccountR"
  "esponse\020\224\010\022\036\n\031k_EMsgGCLookupAccountName\020"
  "\225\010\022&\n!k_EMsgGCLookupAccountNameResponse\020"
  "\226\010\022\035\n\030k_EMsgGCUpdateItemSchema\020\231\010\022 \n\033k_E"
  "MsgGCRemoveCustomTexture\020\233\010\022(\n#k_EMsgGCR"
  "emoveCustomTextureResponse\020\234\010\022\035\n\030k_EMsgG"
  "CRemoveMakersMark\020\235\010\022%\n k_EMsgGCRemoveMa"
  "kersMarkResponse\020\236\010\022#\n\036k_EMsgGCRemoveUni"
  "queCraftIndex\020\237\010\022+\n&k_EMsgGCRemoveUnique"
  "CraftIndexResponse\020\240\010\022\033\n\026k_EMsgGCSaxxyBr"
  "oadcast\020\241\010\022!\n\034k_EMsgGCBackpackSortFinish"
  "ed\020\242\010\022$\n\037k_EMsgGCAdjustItemEquippedState"
  "\020\243\010\022\030\n\023k_EMsgGCCollectItem\020\245\010\022)\n$k_EMsgG"
  "CItemAcknowledged__DEPRECATED\020\246\010\022\031\n\024k_EM"
  "sgGC_ReportAbuse\020\251\010\022!\n\034k_EMsgGC_ReportAb"
  "useResponse\020\252\010\022!\n\034k_EMsgGCNameItemNotifi"
  "cation\020\254\010\022#\n\036k_EMsgGCApplyConsumableEffe"
  "cts\020\255\010\022 \n\033k_EMsgGCConsumableExhausted\020\256\010"
  "\022\036\n\031k_EMsgGCShowItemsPickedUp\020\257\010\022&\n!k_EM"
  "sgGCClientDisplayNotification\020\260\010\022\035\n\030k_EM"
  "sgGCApplyStrangePart\020\261\010\022)\n$k_EMsgGC_Incr"
  "ementKillCountAttribute\020\262\010\022(\n#k_EMsgGC_I"
  "ncrementKillCountResponse\020\263\010\022 \n\033k_EMsgGC"
  "ApplyPennantUpgrade\020\264\010\022\035\n\030k_EMsgGCSetIte"
  "mPositions\020\265\010\022\034\n\027k_EMsgGCApplyEggEssence"
  "\020\266\010\022#\n\036k_EMsgGCNameEggEssenceResponse\020\267\010"
  "\022\031\n\024k_EMsgGCPaintKitItem\020\270\010\022\035\n\030k_EMsgGCP"
  "aintKitBaseItem\020\271\010\022!\n\034k_EMsgGCPaintKitIt"
  "emResponse\020\272\010\022\030\n\023k_EMsgGCGiftedItems\020\273\010\022"
  "\034\n\027k_EMsgGCUnlockItemStyle\020\274\010\022$\n\037k_EMsgG"
  "CUnlockItemStyleResponse\020\275\010\022\031\n\024k_EMsgGCA"
  "pplySticker\020\276\010\022\035\n\030k_EMsgGCItemAcknowledg"
  "ed\020\277\010\022\031\n\024k_EMsgGCStatTrakSwap\020\300\010\022-\n(k_EM"
  "sgGCUserTrackTimePlayedConsecutively\020\301\010\022"
  "\030\n\023k_EMsgGCTradingBase\020\334\013\022)\n$k_EMsgGCTra"
  "ding_InitiateTradeRequest\020\335\013\022*\n%k_EMsgGC"
  "Trading_InitiateTradeResponse\020\336\013\022!\n\034k_EM"
  "sgGCTrading_StartSession\020\337\013\022\034\n\027k_EMsgGCT"
  "rading_SetItem\020\340\013\022\037\n\032k_EMsgGCTrading_Rem"
  "oveItem\020\341\013\022$\n\037k_EMsgGCTrading_UpdateTrad"
  "eInfo\020\342\013\022!\n\034k_EMsgGCTrading_SetReadiness"
  "\020\343\013\022&\n!k_EMsgGCTrading_ReadinessResponse"
  "\020\344\013\022\"\n\035k_EMsgGCTrading_SessionClosed\020\345\013\022"
  "\"\n\035k_EMsgGCTrading_CancelSession\020\346\013\022!\n\034k"
  "_EMsgGCTrading_TradeChatMsg\020\347\013\022!\n\034k_EMsg"
  "GCTrading_ConfirmOffer\020\350\013\022\'\n\"k_EMsgGCTra"
  "ding_TradeTypingChatMsg\020\351\013\022)\n$k_EMsgGCSe"
  "rverBrowser_FavoriteServer\020\301\014\022*\n%k_EMsgG"
  "CServerBrowser_BlacklistServer\020\302\014\022\036\n\031k_E"
  "MsgGCServerRentalsBase\020\244\r\022#\n\036k_EMsgGCIte"
  "mPreviewCheckStatus\020\245\r\022&\n!k_EMsgGCItemPr"
  "eviewStatusResponse\020\246\r\022\037\n\032k_EMsgGCItemPr"
  "eviewRequest\020\247\r\022\'\n\"k_EMsgGCItemPreviewRe"
  "questResponse\020\250\r\022\036\n\031k_EMsgGCItemPreviewE"
  "xpire\020\251\r\022*\n%k_EMsgGCItemPreviewExpireNot"
  "ification\020\252\r\022.\n)k_EMsgGCItemPreviewItemB"
  "oughtNotification\020\253\r\022\037\n\032k_EMsgGCDev_NewI"
  "temRequest\020\321\017\022\'\n\"k_EMsgGCDev_NewItemRequ"
  "estResponse\020\322\017\022!\n\034k_EMsgGCDev_PaintKitDr"
  "opItem\020\323\017\022\035\n\030k_EMsgGCStoreGetUserData\020\304\023"
  "\022%\n k_EMsgGCStoreGetUserDataResponse\020\305\023\022"
  ")\n$k_EMsgGCStorePurchaseInit_DEPRECATED\020"
  "\306\023\0221\n,k_EMsgGCStorePurchaseInitResponse_"
  "DEPRECATED\020\307\023\022\"\n\035k_EMsgGCStorePurchaseFi"
  "nalize\020\310\023\022*\n%k_EMsgGCStorePurchaseFinali"
  "zeResponse\020\311\023\022 \n\033k_EMsgGCStorePurchaseCa"
  "ncel\020\312\023\022(\n#k_EMsgGCStorePurchaseCancelRe"
  "sponse\020\313\023\022\"\n\035k_EMsgGCStorePurchaseQueryT"
  "xn\020\314\023\022*\n%k_EMsgGCStorePurchaseQueryTxnRe"
  "sponse\020\315\023\022\036\n\031k_EMsgGCStorePurchaseInit\020\316"
  "\023\022&\n!k_EMsgGCStorePurchaseInitResponse\020\317"
  "\023\022\"\n\035k_EMsgGCBannedWordListRequest\020\320\023\022#\n"
  "\036k_EMsgGCBannedWordListResponse\020\321\023\022(\n#k_"
  "EMsgGCToGCBannedWordListBroadcast\020\322\023\022&\n!"
  "k_EMsgGCToGCBannedWordListUpdated\020\323\023\022\036\n\031"
  "k_EMsgGCToGCDirtySDOCache\020\324\023\022&\n!k_EMsgGC"
  "ToGCDirtyMultipleSDOCache\020\325\023\022\"\n\035k_EMsgGC"
  "ToGCUpdateSQLKeyValue\020\326\023\022 \n\033k_EMsgGCToGC"
  "IsTrustedServer\020\327\023\022(\n#k_EMsgGCToGCIsTrus"
  "tedServerResponse\020\330\023\022(\n#k_EMsgGCToGCBroa"
  "dcastConsoleCommand\020\331\023\022!\n\034k_EMsgGCServer"
  "VersionUpdated\020\332\023\022\033\n\026k_EMsgGCApplyAutogr"
  "aph\020\333\023\022%\n k_EMsgGCToGCWebAPIAccountChang"
  "ed\020\334\023\022!\n\034k_EMsgGCRequestAnnouncements\020\335\023"
  "\022)\n$k_EMsgGCRequestAnnouncementsResponse"
  "\020\336\023\022%\n k_EMsgGCRequestPassportItemGrant\020"
  "\337\023\022!\n\034k_EMsgGCClientVersionUpdated\020\340\023*\233\002"
  "\n\016EGCMsgResponse\022\026\n\022k_EGCMsgResponseOK\020\000"
  "\022\032\n\026k_EGCMsgResponseDenied\020\001\022\037\n\033k_EGCMsg"
  "ResponseServerError\020\002\022\033\n\027k_EGCMsgRespons"
  "eTimeout\020\003\022\033\n\027k_EGCMsgResponseInvalid\020\004\022"
  "\033\n\027k_EGCMsgResponseNoMatch\020\005\022 \n\034k_EGCMsg"
  "ResponseUnknownError\020\006\022\037\n\033k_EGCMsgRespon"
  "seNotLoggedOn\020\007\022\032\n\026k_EGCMsgFailedToCreat"
  "e\020\010*\351\001\n\014EUnlockStyle\022\033\n\027k_UnlockStyle_Su"
  "cceeded\020\000\022\037\n\033k_UnlockStyle_Failed_PreReq"
  "\020\001\022#\n\037k_UnlockStyle_Failed_CantAfford\020\002\022"
  "#\n\037k_UnlockStyle_Failed_CantCommit\020\003\022&\n\""
  "k_UnlockStyle_Failed_CantLockCache\020\004\022)\n%"
  "k_UnlockStyle_Failed_CantAffordAttrib\020\005B"
  "\005H\001\200\001\000"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_econ_5fgcmessages_2eproto_deps[1] = {
  &::descriptor_table_steammessages_2eproto,
};
static ::_pbi::once_flag descriptor_table_econ_5fgcmessages_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_econ_5fgcmessages_2eproto = {
    false, false, 5726, descriptor_table_protodef_econ_5fgcmessages_2eproto,
    "econ_gcmessages.proto",
    &descriptor_table_econ_5fgcmessages_2eproto_once, descriptor_table_econ_5fgcmessages_2eproto_deps, 1, 3,
    schemas, file_default_instances, TableStruct_econ_5fgcmessages_2eproto::offsets,
    file_level_metadata_econ_5fgcmessages_2eproto, file_level_enum_descriptors_econ_5fgcmessages_2eproto,
    file_level_service_descriptors_econ_5fgcmessages_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_econ_5fgcmessages_2eproto_getter() {
  return &descriptor_table_econ_5fgcmessages_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_econ_5fgcmessages_2eproto(&descriptor_table_econ_5fgcmessages_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCItemMsg_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_econ_5fgcmessages_2eproto);
  return file_level_enum_descriptors_econ_5fgcmessages_2eproto[0];
}
bool EGCItemMsg_IsValid(int value) {
  switch (value) {
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1009:
    case 1010:
    case 1011:
    case 1012:
    case 1013:
    case 1014:
    case 1015:
    case 1016:
    case 1017:
    case 1018:
    case 1019:
    case 1020:
    case 1021:
    case 1022:
    case 1023:
    case 1024:
    case 1025:
    case 1026:
    case 1027:
    case 1030:
    case 1031:
    case 1032:
    case 1033:
    case 1034:
    case 1035:
    case 1036:
    case 1037:
    case 1038:
    case 1039:
    case 1040:
    case 1041:
    case 1042:
    case 1043:
    case 1044:
    case 1045:
    case 1046:
    case 1049:
    case 1051:
    case 1052:
    case 1053:
    case 1054:
    case 1055:
    case 1056:
    case 1057:
    case 1058:
    case 1059:
    case 1061:
    case 1062:
    case 1065:
    case 1066:
    case 1068:
    case 1069:
    case 1070:
    case 1071:
    case 1072:
    case 1073:
    case 1074:
    case 1075:
    case 1076:
    case 1077:
    case 1078:
    case 1079:
    case 1080:
    case 1081:
    case 1082:
    case 1083:
    case 1084:
    case 1085:
    case 1086:
    case 1087:
    case 1088:
    case 1089:
    case 1500:
    case 1501:
    case 1502:
    case 1503:
    case 1504:
    case 1505:
    case 1506:
    case 1507:
    case 1508:
    case 1509:
    case 1510:
    case 1511:
    case 1512:
    case 1513:
    case 1601:
    case 1602:
    case 1700:
    case 1701:
    case 1702:
    case 1703:
    case 1704:
    case 1705:
    case 1706:
    case 1707:
    case 2001:
    case 2002:
    case 2003:
    case 2500:
    case 2501:
    case 2502:
    case 2503:
    case 2504:
    case 2505:
    case 2506:
    case 2507:
    case 2508:
    case 2509:
    case 2510:
    case 2511:
    case 2512:
    case 2513:
    case 2514:
    case 2515:
    case 2516:
    case 2517:
    case 2518:
    case 2519:
    case 2520:
    case 2521:
    case 2522:
    case 2523:
    case 2524:
    case 2525:
    case 2526:
    case 2527:
    case 2528:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCMsgResponse_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_econ_5fgcmessages_2eproto);
  return file_level_enum_descriptors_econ_5fgcmessages_2eproto[1];
}
bool EGCMsgResponse_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EUnlockStyle_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_econ_5fgcmessages_2eproto);
  return file_level_enum_descriptors_econ_5fgcmessages_2eproto[2];
}
bool EUnlockStyle_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class CMsgGCGiftedItems::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgGCGiftedItems>()._impl_._has_bits_);
  static void set_has_accountid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_giftdefindex(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_max_gifts_possible(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_num_eligible_recipients(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

CMsgGCGiftedItems::CMsgGCGiftedItems(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgGCGiftedItems)
}
CMsgGCGiftedItems::CMsgGCGiftedItems(const CMsgGCGiftedItems& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgGCGiftedItems* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.recipients_accountids_){from._impl_.recipients_accountids_}
    , decltype(_impl_.accountid_){}
    , decltype(_impl_.giftdefindex_){}
    , decltype(_impl_.max_gifts_possible_){}
    , decltype(_impl_.num_eligible_recipients_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.accountid_, &from._impl_.accountid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.num_eligible_recipients_) -
    reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.num_eligible_recipients_));
  // @@protoc_insertion_point(copy_constructor:CMsgGCGiftedItems)
}

inline void CMsgGCGiftedItems::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.recipients_accountids_){arena}
    , decltype(_impl_.accountid_){0u}
    , decltype(_impl_.giftdefindex_){0u}
    , decltype(_impl_.max_gifts_possible_){0u}
    , decltype(_impl_.num_eligible_recipients_){0u}
  };
}

CMsgGCGiftedItems::~CMsgGCGiftedItems() {
  // @@protoc_insertion_point(destructor:CMsgGCGiftedItems)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgGCGiftedItems::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.recipients_accountids_.~RepeatedField();
}

void CMsgGCGiftedItems::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgGCGiftedItems::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCGiftedItems)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.recipients_accountids_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&_impl_.accountid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.num_eligible_recipients_) -
        reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.num_eligible_recipients_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgGCGiftedItems::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 accountid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_accountid(&has_bits);
          _impl_.accountid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 giftdefindex = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_giftdefindex(&has_bits);
          _impl_.giftdefindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 max_gifts_possible = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_max_gifts_possible(&has_bits);
          _impl_.max_gifts_possible_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 num_eligible_recipients = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_num_eligible_recipients(&has_bits);
          _impl_.num_eligible_recipients_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 recipients_accountids = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_recipients_accountids(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<40>(ptr));
        } else if (static_cast<uint8_t>(tag) == 42) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_recipients_accountids(), ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgGCGiftedItems::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCGiftedItems)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 accountid = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_accountid(), target);
  }

  // optional uint32 giftdefindex = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_giftdefindex(), target);
  }

  // optional uint32 max_gifts_possible = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_max_gifts_possible(), target);
  }

  // optional uint32 num_eligible_recipients = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_num_eligible_recipients(), target);
  }

  // repeated uint32 recipients_accountids = 5;
  for (int i = 0, n = this->_internal_recipients_accountids_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_recipients_accountids(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCGiftedItems)
  return target;
}

size_t CMsgGCGiftedItems::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgGCGiftedItems)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 recipients_accountids = 5;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->_impl_.recipients_accountids_);
    total_size += 1 *
                  ::_pbi::FromIntSize(this->_internal_recipients_accountids_size());
    total_size += data_size;
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional uint32 accountid = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_accountid());
    }

    // optional uint32 giftdefindex = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_giftdefindex());
    }

    // optional uint32 max_gifts_possible = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_max_gifts_possible());
    }

    // optional uint32 num_eligible_recipients = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_num_eligible_recipients());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgGCGiftedItems::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgGCGiftedItems::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgGCGiftedItems::GetClassData() const { return &_class_data_; }


void CMsgGCGiftedItems::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgGCGiftedItems*>(&to_msg);
  auto& from = static_cast<const CMsgGCGiftedItems&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCGiftedItems)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.recipients_accountids_.MergeFrom(from._impl_.recipients_accountids_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.accountid_ = from._impl_.accountid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.giftdefindex_ = from._impl_.giftdefindex_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.max_gifts_possible_ = from._impl_.max_gifts_possible_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.num_eligible_recipients_ = from._impl_.num_eligible_recipients_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgGCGiftedItems::CopyFrom(const CMsgGCGiftedItems& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCGiftedItems)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgGCGiftedItems::IsInitialized() const {
  return true;
}

void CMsgGCGiftedItems::InternalSwap(CMsgGCGiftedItems* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.recipients_accountids_.InternalSwap(&other->_impl_.recipients_accountids_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.num_eligible_recipients_)
      + sizeof(CMsgGCGiftedItems::_impl_.num_eligible_recipients_)
      - PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.accountid_)>(
          reinterpret_cast<char*>(&_impl_.accountid_),
          reinterpret_cast<char*>(&other->_impl_.accountid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgGCGiftedItems::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_econ_5fgcmessages_2eproto_getter, &descriptor_table_econ_5fgcmessages_2eproto_once,
      file_level_metadata_econ_5fgcmessages_2eproto[0]);
}

// ===================================================================

class CMsgApplyAutograph::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgApplyAutograph>()._impl_._has_bits_);
  static void set_has_autograph_item_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_item_item_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

CMsgApplyAutograph::CMsgApplyAutograph(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgApplyAutograph)
}
CMsgApplyAutograph::CMsgApplyAutograph(const CMsgApplyAutograph& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgApplyAutograph* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.autograph_item_id_){}
    , decltype(_impl_.item_item_id_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.autograph_item_id_, &from._impl_.autograph_item_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.item_item_id_) -
    reinterpret_cast<char*>(&_impl_.autograph_item_id_)) + sizeof(_impl_.item_item_id_));
  // @@protoc_insertion_point(copy_constructor:CMsgApplyAutograph)
}

inline void CMsgApplyAutograph::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.autograph_item_id_){uint64_t{0u}}
    , decltype(_impl_.item_item_id_){uint64_t{0u}}
  };
}

CMsgApplyAutograph::~CMsgApplyAutograph() {
  // @@protoc_insertion_point(destructor:CMsgApplyAutograph)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgApplyAutograph::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgApplyAutograph::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgApplyAutograph::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgApplyAutograph)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.autograph_item_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.item_item_id_) -
        reinterpret_cast<char*>(&_impl_.autograph_item_id_)) + sizeof(_impl_.item_item_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgApplyAutograph::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint64 autograph_item_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_autograph_item_id(&has_bits);
          _impl_.autograph_item_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 item_item_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_item_item_id(&has_bits);
          _impl_.item_item_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgApplyAutograph::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgApplyAutograph)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint64 autograph_item_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_autograph_item_id(), target);
  }

  // optional uint64 item_item_id = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_item_item_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgApplyAutograph)
  return target;
}

size_t CMsgApplyAutograph::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgApplyAutograph)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional uint64 autograph_item_id = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_autograph_item_id());
    }

    // optional uint64 item_item_id = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_item_item_id());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgApplyAutograph::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgApplyAutograph::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgApplyAutograph::GetClassData() const { return &_class_data_; }


void CMsgApplyAutograph::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgApplyAutograph*>(&to_msg);
  auto& from = static_cast<const CMsgApplyAutograph&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgApplyAutograph)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.autograph_item_id_ = from._impl_.autograph_item_id_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.item_item_id_ = from._impl_.item_item_id_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgApplyAutograph::CopyFrom(const CMsgApplyAutograph& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgApplyAutograph)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgApplyAutograph::IsInitialized() const {
  return true;
}

void CMsgApplyAutograph::InternalSwap(CMsgApplyAutograph* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgApplyAutograph, _impl_.item_item_id_)
      + sizeof(CMsgApplyAutograph::_impl_.item_item_id_)
      - PROTOBUF_FIELD_OFFSET(CMsgApplyAutograph, _impl_.autograph_item_id_)>(
          reinterpret_cast<char*>(&_impl_.autograph_item_id_),
          reinterpret_cast<char*>(&other->_impl_.autograph_item_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgApplyAutograph::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_econ_5fgcmessages_2eproto_getter, &descriptor_table_econ_5fgcmessages_2eproto_once,
      file_level_metadata_econ_5fgcmessages_2eproto[1]);
}

// ===================================================================

class CMsgGCUserTrackTimePlayedConsecutively::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgGCUserTrackTimePlayedConsecutively>()._impl_._has_bits_);
  static void set_has_state(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CMsgGCUserTrackTimePlayedConsecutively::CMsgGCUserTrackTimePlayedConsecutively(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgGCUserTrackTimePlayedConsecutively)
}
CMsgGCUserTrackTimePlayedConsecutively::CMsgGCUserTrackTimePlayedConsecutively(const CMsgGCUserTrackTimePlayedConsecutively& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgGCUserTrackTimePlayedConsecutively* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.state_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.state_ = from._impl_.state_;
  // @@protoc_insertion_point(copy_constructor:CMsgGCUserTrackTimePlayedConsecutively)
}

inline void CMsgGCUserTrackTimePlayedConsecutively::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.state_){0u}
  };
}

CMsgGCUserTrackTimePlayedConsecutively::~CMsgGCUserTrackTimePlayedConsecutively() {
  // @@protoc_insertion_point(destructor:CMsgGCUserTrackTimePlayedConsecutively)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgGCUserTrackTimePlayedConsecutively::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgGCUserTrackTimePlayedConsecutively::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgGCUserTrackTimePlayedConsecutively::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCUserTrackTimePlayedConsecutively)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.state_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgGCUserTrackTimePlayedConsecutively::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_state(&has_bits);
          _impl_.state_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgGCUserTrackTimePlayedConsecutively::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCUserTrackTimePlayedConsecutively)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 state = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCUserTrackTimePlayedConsecutively)
  return target;
}

size_t CMsgGCUserTrackTimePlayedConsecutively::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgGCUserTrackTimePlayedConsecutively)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional uint32 state = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgGCUserTrackTimePlayedConsecutively::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgGCUserTrackTimePlayedConsecutively::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgGCUserTrackTimePlayedConsecutively::GetClassData() const { return &_class_data_; }


void CMsgGCUserTrackTimePlayedConsecutively::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgGCUserTrackTimePlayedConsecutively*>(&to_msg);
  auto& from = static_cast<const CMsgGCUserTrackTimePlayedConsecutively&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCUserTrackTimePlayedConsecutively)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_state()) {
    _this->_internal_set_state(from._internal_state());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgGCUserTrackTimePlayedConsecutively::CopyFrom(const CMsgGCUserTrackTimePlayedConsecutively& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCUserTrackTimePlayedConsecutively)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgGCUserTrackTimePlayedConsecutively::IsInitialized() const {
  return true;
}

void CMsgGCUserTrackTimePlayedConsecutively::InternalSwap(CMsgGCUserTrackTimePlayedConsecutively* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.state_, other->_impl_.state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgGCUserTrackTimePlayedConsecutively::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_econ_5fgcmessages_2eproto_getter, &descriptor_table_econ_5fgcmessages_2eproto_once,
      file_level_metadata_econ_5fgcmessages_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CMsgGCGiftedItems*
Arena::CreateMaybeMessage< ::CMsgGCGiftedItems >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgGCGiftedItems >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgApplyAutograph*
Arena::CreateMaybeMessage< ::CMsgApplyAutograph >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgApplyAutograph >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgGCUserTrackTimePlayedConsecutively*
Arena::CreateMaybeMessage< ::CMsgGCUserTrackTimePlayedConsecutively >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgGCUserTrackTimePlayedConsecutively >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
