// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gcsystemmsgs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_gcsystemmsgs_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_gcsystemmsgs_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_gcsystemmsgs_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_gcsystemmsgs_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gcsystemmsgs_2eproto;
class CMsgGCHAccountPhoneNumberChange;
struct CMsgGCHAccountPhoneNumberChangeDefaultTypeInternal;
extern CMsgGCHAccountPhoneNumberChangeDefaultTypeInternal _CMsgGCHAccountPhoneNumberChange_default_instance_;
class CMsgGCHInviteUserToLobby;
struct CMsgGCHInviteUserToLobbyDefaultTypeInternal;
extern CMsgGCHInviteUserToLobbyDefaultTypeInternal _CMsgGCHInviteUserToLobby_default_instance_;
class CMsgGCHVacVerificationChange;
struct CMsgGCHVacVerificationChangeDefaultTypeInternal;
extern CMsgGCHVacVerificationChangeDefaultTypeInternal _CMsgGCHVacVerificationChange_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CMsgGCHAccountPhoneNumberChange* Arena::CreateMaybeMessage<::CMsgGCHAccountPhoneNumberChange>(Arena*);
template<> ::CMsgGCHInviteUserToLobby* Arena::CreateMaybeMessage<::CMsgGCHInviteUserToLobby>(Arena*);
template<> ::CMsgGCHVacVerificationChange* Arena::CreateMaybeMessage<::CMsgGCHVacVerificationChange>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum EGCSystemMsg : int {
  k_EGCMsgInvalid = 0,
  k_EGCMsgMulti = 1,
  k_EGCMsgGenericReply = 10,
  k_EGCMsgSystemBase = 50,
  k_EGCMsgAchievementAwarded = 51,
  k_EGCMsgConCommand = 52,
  k_EGCMsgStartPlaying = 53,
  k_EGCMsgStopPlaying = 54,
  k_EGCMsgStartGameserver = 55,
  k_EGCMsgStopGameserver = 56,
  k_EGCMsgWGRequest = 57,
  k_EGCMsgWGResponse = 58,
  k_EGCMsgGetUserGameStatsSchema = 59,
  k_EGCMsgGetUserGameStatsSchemaResponse = 60,
  k_EGCMsgGetUserStatsDEPRECATED = 61,
  k_EGCMsgGetUserStatsResponse = 62,
  k_EGCMsgAppInfoUpdated = 63,
  k_EGCMsgValidateSession = 64,
  k_EGCMsgValidateSessionResponse = 65,
  k_EGCMsgLookupAccountFromInput = 66,
  k_EGCMsgSendHTTPRequest = 67,
  k_EGCMsgSendHTTPRequestResponse = 68,
  k_EGCMsgPreTestSetup = 69,
  k_EGCMsgRecordSupportAction = 70,
  k_EGCMsgGetAccountDetails_DEPRECATED = 71,
  k_EGCMsgReceiveInterAppMessage = 73,
  k_EGCMsgFindAccounts = 74,
  k_EGCMsgPostAlert = 75,
  k_EGCMsgGetLicenses = 76,
  k_EGCMsgGetUserStats = 77,
  k_EGCMsgGetCommands = 78,
  k_EGCMsgGetCommandsResponse = 79,
  k_EGCMsgAddFreeLicense = 80,
  k_EGCMsgAddFreeLicenseResponse = 81,
  k_EGCMsgGetIPLocation = 82,
  k_EGCMsgGetIPLocationResponse = 83,
  k_EGCMsgSystemStatsSchema = 84,
  k_EGCMsgGetSystemStats = 85,
  k_EGCMsgGetSystemStatsResponse = 86,
  k_EGCMsgSendEmail = 87,
  k_EGCMsgSendEmailResponse = 88,
  k_EGCMsgGetEmailTemplate = 89,
  k_EGCMsgGetEmailTemplateResponse = 90,
  k_EGCMsgGrantGuestPass = 91,
  k_EGCMsgGrantGuestPassResponse = 92,
  k_EGCMsgGetAccountDetails = 93,
  k_EGCMsgGetAccountDetailsResponse = 94,
  k_EGCMsgGetPersonaNames = 95,
  k_EGCMsgGetPersonaNamesResponse = 96,
  k_EGCMsgMultiplexMsg = 97,
  k_EGCMsgMultiplexMsgResponse = 98,
  k_EGCMsgWebAPIRegisterInterfaces = 101,
  k_EGCMsgWebAPIJobRequest = 102,
  k_EGCMsgWebAPIJobRequestHttpResponse = 104,
  k_EGCMsgWebAPIJobRequestForwardResponse = 105,
  k_EGCMsgMemCachedGet = 200,
  k_EGCMsgMemCachedGetResponse = 201,
  k_EGCMsgMemCachedSet = 202,
  k_EGCMsgMemCachedDelete = 203,
  k_EGCMsgMemCachedStats = 204,
  k_EGCMsgMemCachedStatsResponse = 205,
  k_EGCMsgMasterSetDirectory = 220,
  k_EGCMsgMasterSetDirectoryResponse = 221,
  k_EGCMsgMasterSetWebAPIRouting = 222,
  k_EGCMsgMasterSetWebAPIRoutingResponse = 223,
  k_EGCMsgMasterSetClientMsgRouting = 224,
  k_EGCMsgMasterSetClientMsgRoutingResponse = 225,
  k_EGCMsgSetOptions = 226,
  k_EGCMsgSetOptionsResponse = 227,
  k_EGCMsgSystemBase2 = 500,
  k_EGCMsgGetPurchaseTrustStatus = 501,
  k_EGCMsgGetPurchaseTrustStatusResponse = 502,
  k_EGCMsgUpdateSession = 503,
  k_EGCMsgGCAccountVacStatusChange = 504,
  k_EGCMsgCheckFriendship = 505,
  k_EGCMsgCheckFriendshipResponse = 506,
  k_EGCMsgGetPartnerAccountLink = 507,
  k_EGCMsgGetPartnerAccountLinkResponse = 508,
  k_EGCMsgVacVerificationChange = 518,
  k_EGCMsgAccountPhoneNumberChange = 519,
  k_EGCMsgInviteUserToLobby = 523
};
bool EGCSystemMsg_IsValid(int value);
constexpr EGCSystemMsg EGCSystemMsg_MIN = k_EGCMsgInvalid;
constexpr EGCSystemMsg EGCSystemMsg_MAX = k_EGCMsgInviteUserToLobby;
constexpr int EGCSystemMsg_ARRAYSIZE = EGCSystemMsg_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCSystemMsg_descriptor();
template<typename T>
inline const std::string& EGCSystemMsg_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EGCSystemMsg>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EGCSystemMsg_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EGCSystemMsg_descriptor(), enum_t_value);
}
inline bool EGCSystemMsg_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EGCSystemMsg* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EGCSystemMsg>(
    EGCSystemMsg_descriptor(), name, value);
}
enum ESOMsg : int {
  k_ESOMsg_Create = 21,
  k_ESOMsg_Update = 22,
  k_ESOMsg_Destroy = 23,
  k_ESOMsg_CacheSubscribed = 24,
  k_ESOMsg_CacheUnsubscribed = 25,
  k_ESOMsg_UpdateMultiple = 26,
  k_ESOMsg_CacheSubscriptionCheck = 27,
  k_ESOMsg_CacheSubscriptionRefresh = 28
};
bool ESOMsg_IsValid(int value);
constexpr ESOMsg ESOMsg_MIN = k_ESOMsg_Create;
constexpr ESOMsg ESOMsg_MAX = k_ESOMsg_CacheSubscriptionRefresh;
constexpr int ESOMsg_ARRAYSIZE = ESOMsg_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESOMsg_descriptor();
template<typename T>
inline const std::string& ESOMsg_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ESOMsg>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ESOMsg_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ESOMsg_descriptor(), enum_t_value);
}
inline bool ESOMsg_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ESOMsg* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ESOMsg>(
    ESOMsg_descriptor(), name, value);
}
enum EGCBaseClientMsg : int {
  k_EMsgGCClientWelcome = 4004,
  k_EMsgGCServerWelcome = 4005,
  k_EMsgGCClientHello = 4006,
  k_EMsgGCServerHello = 4007,
  k_EMsgGCClientConnectionStatus = 4009,
  k_EMsgGCServerConnectionStatus = 4010,
  k_EMsgGCClientHelloPartner = 4011,
  k_EMsgGCClientHelloPW = 4012,
  k_EMsgGCClientHelloR2 = 4013,
  k_EMsgGCClientHelloR3 = 4014,
  k_EMsgGCClientHelloR4 = 4015
};
bool EGCBaseClientMsg_IsValid(int value);
constexpr EGCBaseClientMsg EGCBaseClientMsg_MIN = k_EMsgGCClientWelcome;
constexpr EGCBaseClientMsg EGCBaseClientMsg_MAX = k_EMsgGCClientHelloR4;
constexpr int EGCBaseClientMsg_ARRAYSIZE = EGCBaseClientMsg_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCBaseClientMsg_descriptor();
template<typename T>
inline const std::string& EGCBaseClientMsg_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EGCBaseClientMsg>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EGCBaseClientMsg_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EGCBaseClientMsg_descriptor(), enum_t_value);
}
inline bool EGCBaseClientMsg_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EGCBaseClientMsg* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EGCBaseClientMsg>(
    EGCBaseClientMsg_descriptor(), name, value);
}
enum EGCToGCMsg : int {
  k_EGCToGCMsgMasterAck = 150,
  k_EGCToGCMsgMasterAckResponse = 151,
  k_EGCToGCMsgRouted = 152,
  k_EGCToGCMsgRoutedReply = 153,
  k_EMsgUpdateSessionIP = 154,
  k_EMsgRequestSessionIP = 155,
  k_EMsgRequestSessionIPResponse = 156,
  k_EGCToGCMsgMasterStartupComplete = 157
};
bool EGCToGCMsg_IsValid(int value);
constexpr EGCToGCMsg EGCToGCMsg_MIN = k_EGCToGCMsgMasterAck;
constexpr EGCToGCMsg EGCToGCMsg_MAX = k_EGCToGCMsgMasterStartupComplete;
constexpr int EGCToGCMsg_ARRAYSIZE = EGCToGCMsg_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCToGCMsg_descriptor();
template<typename T>
inline const std::string& EGCToGCMsg_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EGCToGCMsg>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EGCToGCMsg_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EGCToGCMsg_descriptor(), enum_t_value);
}
inline bool EGCToGCMsg_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EGCToGCMsg* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EGCToGCMsg>(
    EGCToGCMsg_descriptor(), name, value);
}
// ===================================================================

class CMsgGCHVacVerificationChange final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgGCHVacVerificationChange) */ {
 public:
  inline CMsgGCHVacVerificationChange() : CMsgGCHVacVerificationChange(nullptr) {}
  ~CMsgGCHVacVerificationChange() override;
  explicit PROTOBUF_CONSTEXPR CMsgGCHVacVerificationChange(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgGCHVacVerificationChange(const CMsgGCHVacVerificationChange& from);
  CMsgGCHVacVerificationChange(CMsgGCHVacVerificationChange&& from) noexcept
    : CMsgGCHVacVerificationChange() {
    *this = ::std::move(from);
  }

  inline CMsgGCHVacVerificationChange& operator=(const CMsgGCHVacVerificationChange& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCHVacVerificationChange& operator=(CMsgGCHVacVerificationChange&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgGCHVacVerificationChange& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgGCHVacVerificationChange* internal_default_instance() {
    return reinterpret_cast<const CMsgGCHVacVerificationChange*>(
               &_CMsgGCHVacVerificationChange_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CMsgGCHVacVerificationChange& a, CMsgGCHVacVerificationChange& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgGCHVacVerificationChange* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCHVacVerificationChange* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgGCHVacVerificationChange* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgGCHVacVerificationChange>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgGCHVacVerificationChange& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgGCHVacVerificationChange& from) {
    CMsgGCHVacVerificationChange::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgGCHVacVerificationChange* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgGCHVacVerificationChange";
  }
  protected:
  explicit CMsgGCHVacVerificationChange(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSteamidFieldNumber = 1,
    kAppidFieldNumber = 2,
    kIsVerifiedFieldNumber = 3,
  };
  // optional fixed64 steamid = 1;
  bool has_steamid() const;
  private:
  bool _internal_has_steamid() const;
  public:
  void clear_steamid();
  uint64_t steamid() const;
  void set_steamid(uint64_t value);
  private:
  uint64_t _internal_steamid() const;
  void _internal_set_steamid(uint64_t value);
  public:

  // optional uint32 appid = 2;
  bool has_appid() const;
  private:
  bool _internal_has_appid() const;
  public:
  void clear_appid();
  uint32_t appid() const;
  void set_appid(uint32_t value);
  private:
  uint32_t _internal_appid() const;
  void _internal_set_appid(uint32_t value);
  public:

  // optional bool is_verified = 3;
  bool has_is_verified() const;
  private:
  bool _internal_has_is_verified() const;
  public:
  void clear_is_verified();
  bool is_verified() const;
  void set_is_verified(bool value);
  private:
  bool _internal_is_verified() const;
  void _internal_set_is_verified(bool value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgGCHVacVerificationChange)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint64_t steamid_;
    uint32_t appid_;
    bool is_verified_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gcsystemmsgs_2eproto;
};
// -------------------------------------------------------------------

class CMsgGCHAccountPhoneNumberChange final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgGCHAccountPhoneNumberChange) */ {
 public:
  inline CMsgGCHAccountPhoneNumberChange() : CMsgGCHAccountPhoneNumberChange(nullptr) {}
  ~CMsgGCHAccountPhoneNumberChange() override;
  explicit PROTOBUF_CONSTEXPR CMsgGCHAccountPhoneNumberChange(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgGCHAccountPhoneNumberChange(const CMsgGCHAccountPhoneNumberChange& from);
  CMsgGCHAccountPhoneNumberChange(CMsgGCHAccountPhoneNumberChange&& from) noexcept
    : CMsgGCHAccountPhoneNumberChange() {
    *this = ::std::move(from);
  }

  inline CMsgGCHAccountPhoneNumberChange& operator=(const CMsgGCHAccountPhoneNumberChange& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCHAccountPhoneNumberChange& operator=(CMsgGCHAccountPhoneNumberChange&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgGCHAccountPhoneNumberChange& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgGCHAccountPhoneNumberChange* internal_default_instance() {
    return reinterpret_cast<const CMsgGCHAccountPhoneNumberChange*>(
               &_CMsgGCHAccountPhoneNumberChange_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CMsgGCHAccountPhoneNumberChange& a, CMsgGCHAccountPhoneNumberChange& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgGCHAccountPhoneNumberChange* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCHAccountPhoneNumberChange* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgGCHAccountPhoneNumberChange* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgGCHAccountPhoneNumberChange>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgGCHAccountPhoneNumberChange& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgGCHAccountPhoneNumberChange& from) {
    CMsgGCHAccountPhoneNumberChange::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgGCHAccountPhoneNumberChange* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgGCHAccountPhoneNumberChange";
  }
  protected:
  explicit CMsgGCHAccountPhoneNumberChange(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSteamidFieldNumber = 1,
    kPhoneIdFieldNumber = 3,
    kAppidFieldNumber = 2,
    kIsVerifiedFieldNumber = 4,
    kIsIdentifyingFieldNumber = 5,
  };
  // optional fixed64 steamid = 1;
  bool has_steamid() const;
  private:
  bool _internal_has_steamid() const;
  public:
  void clear_steamid();
  uint64_t steamid() const;
  void set_steamid(uint64_t value);
  private:
  uint64_t _internal_steamid() const;
  void _internal_set_steamid(uint64_t value);
  public:

  // optional uint64 phone_id = 3;
  bool has_phone_id() const;
  private:
  bool _internal_has_phone_id() const;
  public:
  void clear_phone_id();
  uint64_t phone_id() const;
  void set_phone_id(uint64_t value);
  private:
  uint64_t _internal_phone_id() const;
  void _internal_set_phone_id(uint64_t value);
  public:

  // optional uint32 appid = 2;
  bool has_appid() const;
  private:
  bool _internal_has_appid() const;
  public:
  void clear_appid();
  uint32_t appid() const;
  void set_appid(uint32_t value);
  private:
  uint32_t _internal_appid() const;
  void _internal_set_appid(uint32_t value);
  public:

  // optional bool is_verified = 4;
  bool has_is_verified() const;
  private:
  bool _internal_has_is_verified() const;
  public:
  void clear_is_verified();
  bool is_verified() const;
  void set_is_verified(bool value);
  private:
  bool _internal_is_verified() const;
  void _internal_set_is_verified(bool value);
  public:

  // optional bool is_identifying = 5;
  bool has_is_identifying() const;
  private:
  bool _internal_has_is_identifying() const;
  public:
  void clear_is_identifying();
  bool is_identifying() const;
  void set_is_identifying(bool value);
  private:
  bool _internal_is_identifying() const;
  void _internal_set_is_identifying(bool value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgGCHAccountPhoneNumberChange)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint64_t steamid_;
    uint64_t phone_id_;
    uint32_t appid_;
    bool is_verified_;
    bool is_identifying_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gcsystemmsgs_2eproto;
};
// -------------------------------------------------------------------

class CMsgGCHInviteUserToLobby final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgGCHInviteUserToLobby) */ {
 public:
  inline CMsgGCHInviteUserToLobby() : CMsgGCHInviteUserToLobby(nullptr) {}
  ~CMsgGCHInviteUserToLobby() override;
  explicit PROTOBUF_CONSTEXPR CMsgGCHInviteUserToLobby(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgGCHInviteUserToLobby(const CMsgGCHInviteUserToLobby& from);
  CMsgGCHInviteUserToLobby(CMsgGCHInviteUserToLobby&& from) noexcept
    : CMsgGCHInviteUserToLobby() {
    *this = ::std::move(from);
  }

  inline CMsgGCHInviteUserToLobby& operator=(const CMsgGCHInviteUserToLobby& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCHInviteUserToLobby& operator=(CMsgGCHInviteUserToLobby&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgGCHInviteUserToLobby& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgGCHInviteUserToLobby* internal_default_instance() {
    return reinterpret_cast<const CMsgGCHInviteUserToLobby*>(
               &_CMsgGCHInviteUserToLobby_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CMsgGCHInviteUserToLobby& a, CMsgGCHInviteUserToLobby& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgGCHInviteUserToLobby* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCHInviteUserToLobby* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgGCHInviteUserToLobby* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgGCHInviteUserToLobby>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgGCHInviteUserToLobby& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgGCHInviteUserToLobby& from) {
    CMsgGCHInviteUserToLobby::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgGCHInviteUserToLobby* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgGCHInviteUserToLobby";
  }
  protected:
  explicit CMsgGCHInviteUserToLobby(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSteamidFieldNumber = 1,
    kSteamidInvitedFieldNumber = 3,
    kSteamidLobbyFieldNumber = 4,
    kAppidFieldNumber = 2,
  };
  // optional fixed64 steamid = 1;
  bool has_steamid() const;
  private:
  bool _internal_has_steamid() const;
  public:
  void clear_steamid();
  uint64_t steamid() const;
  void set_steamid(uint64_t value);
  private:
  uint64_t _internal_steamid() const;
  void _internal_set_steamid(uint64_t value);
  public:

  // optional fixed64 steamid_invited = 3;
  bool has_steamid_invited() const;
  private:
  bool _internal_has_steamid_invited() const;
  public:
  void clear_steamid_invited();
  uint64_t steamid_invited() const;
  void set_steamid_invited(uint64_t value);
  private:
  uint64_t _internal_steamid_invited() const;
  void _internal_set_steamid_invited(uint64_t value);
  public:

  // optional fixed64 steamid_lobby = 4;
  bool has_steamid_lobby() const;
  private:
  bool _internal_has_steamid_lobby() const;
  public:
  void clear_steamid_lobby();
  uint64_t steamid_lobby() const;
  void set_steamid_lobby(uint64_t value);
  private:
  uint64_t _internal_steamid_lobby() const;
  void _internal_set_steamid_lobby(uint64_t value);
  public:

  // optional uint32 appid = 2;
  bool has_appid() const;
  private:
  bool _internal_has_appid() const;
  public:
  void clear_appid();
  uint32_t appid() const;
  void set_appid(uint32_t value);
  private:
  uint32_t _internal_appid() const;
  void _internal_set_appid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgGCHInviteUserToLobby)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint64_t steamid_;
    uint64_t steamid_invited_;
    uint64_t steamid_lobby_;
    uint32_t appid_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gcsystemmsgs_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CMsgGCHVacVerificationChange

// optional fixed64 steamid = 1;
inline bool CMsgGCHVacVerificationChange::_internal_has_steamid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgGCHVacVerificationChange::has_steamid() const {
  return _internal_has_steamid();
}
inline void CMsgGCHVacVerificationChange::clear_steamid() {
  _impl_.steamid_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint64_t CMsgGCHVacVerificationChange::_internal_steamid() const {
  return _impl_.steamid_;
}
inline uint64_t CMsgGCHVacVerificationChange::steamid() const {
  // @@protoc_insertion_point(field_get:CMsgGCHVacVerificationChange.steamid)
  return _internal_steamid();
}
inline void CMsgGCHVacVerificationChange::_internal_set_steamid(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.steamid_ = value;
}
inline void CMsgGCHVacVerificationChange::set_steamid(uint64_t value) {
  _internal_set_steamid(value);
  // @@protoc_insertion_point(field_set:CMsgGCHVacVerificationChange.steamid)
}

// optional uint32 appid = 2;
inline bool CMsgGCHVacVerificationChange::_internal_has_appid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgGCHVacVerificationChange::has_appid() const {
  return _internal_has_appid();
}
inline void CMsgGCHVacVerificationChange::clear_appid() {
  _impl_.appid_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t CMsgGCHVacVerificationChange::_internal_appid() const {
  return _impl_.appid_;
}
inline uint32_t CMsgGCHVacVerificationChange::appid() const {
  // @@protoc_insertion_point(field_get:CMsgGCHVacVerificationChange.appid)
  return _internal_appid();
}
inline void CMsgGCHVacVerificationChange::_internal_set_appid(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.appid_ = value;
}
inline void CMsgGCHVacVerificationChange::set_appid(uint32_t value) {
  _internal_set_appid(value);
  // @@protoc_insertion_point(field_set:CMsgGCHVacVerificationChange.appid)
}

// optional bool is_verified = 3;
inline bool CMsgGCHVacVerificationChange::_internal_has_is_verified() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CMsgGCHVacVerificationChange::has_is_verified() const {
  return _internal_has_is_verified();
}
inline void CMsgGCHVacVerificationChange::clear_is_verified() {
  _impl_.is_verified_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool CMsgGCHVacVerificationChange::_internal_is_verified() const {
  return _impl_.is_verified_;
}
inline bool CMsgGCHVacVerificationChange::is_verified() const {
  // @@protoc_insertion_point(field_get:CMsgGCHVacVerificationChange.is_verified)
  return _internal_is_verified();
}
inline void CMsgGCHVacVerificationChange::_internal_set_is_verified(bool value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.is_verified_ = value;
}
inline void CMsgGCHVacVerificationChange::set_is_verified(bool value) {
  _internal_set_is_verified(value);
  // @@protoc_insertion_point(field_set:CMsgGCHVacVerificationChange.is_verified)
}

// -------------------------------------------------------------------

// CMsgGCHAccountPhoneNumberChange

// optional fixed64 steamid = 1;
inline bool CMsgGCHAccountPhoneNumberChange::_internal_has_steamid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgGCHAccountPhoneNumberChange::has_steamid() const {
  return _internal_has_steamid();
}
inline void CMsgGCHAccountPhoneNumberChange::clear_steamid() {
  _impl_.steamid_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint64_t CMsgGCHAccountPhoneNumberChange::_internal_steamid() const {
  return _impl_.steamid_;
}
inline uint64_t CMsgGCHAccountPhoneNumberChange::steamid() const {
  // @@protoc_insertion_point(field_get:CMsgGCHAccountPhoneNumberChange.steamid)
  return _internal_steamid();
}
inline void CMsgGCHAccountPhoneNumberChange::_internal_set_steamid(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.steamid_ = value;
}
inline void CMsgGCHAccountPhoneNumberChange::set_steamid(uint64_t value) {
  _internal_set_steamid(value);
  // @@protoc_insertion_point(field_set:CMsgGCHAccountPhoneNumberChange.steamid)
}

// optional uint32 appid = 2;
inline bool CMsgGCHAccountPhoneNumberChange::_internal_has_appid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CMsgGCHAccountPhoneNumberChange::has_appid() const {
  return _internal_has_appid();
}
inline void CMsgGCHAccountPhoneNumberChange::clear_appid() {
  _impl_.appid_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t CMsgGCHAccountPhoneNumberChange::_internal_appid() const {
  return _impl_.appid_;
}
inline uint32_t CMsgGCHAccountPhoneNumberChange::appid() const {
  // @@protoc_insertion_point(field_get:CMsgGCHAccountPhoneNumberChange.appid)
  return _internal_appid();
}
inline void CMsgGCHAccountPhoneNumberChange::_internal_set_appid(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.appid_ = value;
}
inline void CMsgGCHAccountPhoneNumberChange::set_appid(uint32_t value) {
  _internal_set_appid(value);
  // @@protoc_insertion_point(field_set:CMsgGCHAccountPhoneNumberChange.appid)
}

// optional uint64 phone_id = 3;
inline bool CMsgGCHAccountPhoneNumberChange::_internal_has_phone_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgGCHAccountPhoneNumberChange::has_phone_id() const {
  return _internal_has_phone_id();
}
inline void CMsgGCHAccountPhoneNumberChange::clear_phone_id() {
  _impl_.phone_id_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint64_t CMsgGCHAccountPhoneNumberChange::_internal_phone_id() const {
  return _impl_.phone_id_;
}
inline uint64_t CMsgGCHAccountPhoneNumberChange::phone_id() const {
  // @@protoc_insertion_point(field_get:CMsgGCHAccountPhoneNumberChange.phone_id)
  return _internal_phone_id();
}
inline void CMsgGCHAccountPhoneNumberChange::_internal_set_phone_id(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.phone_id_ = value;
}
inline void CMsgGCHAccountPhoneNumberChange::set_phone_id(uint64_t value) {
  _internal_set_phone_id(value);
  // @@protoc_insertion_point(field_set:CMsgGCHAccountPhoneNumberChange.phone_id)
}

// optional bool is_verified = 4;
inline bool CMsgGCHAccountPhoneNumberChange::_internal_has_is_verified() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CMsgGCHAccountPhoneNumberChange::has_is_verified() const {
  return _internal_has_is_verified();
}
inline void CMsgGCHAccountPhoneNumberChange::clear_is_verified() {
  _impl_.is_verified_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool CMsgGCHAccountPhoneNumberChange::_internal_is_verified() const {
  return _impl_.is_verified_;
}
inline bool CMsgGCHAccountPhoneNumberChange::is_verified() const {
  // @@protoc_insertion_point(field_get:CMsgGCHAccountPhoneNumberChange.is_verified)
  return _internal_is_verified();
}
inline void CMsgGCHAccountPhoneNumberChange::_internal_set_is_verified(bool value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.is_verified_ = value;
}
inline void CMsgGCHAccountPhoneNumberChange::set_is_verified(bool value) {
  _internal_set_is_verified(value);
  // @@protoc_insertion_point(field_set:CMsgGCHAccountPhoneNumberChange.is_verified)
}

// optional bool is_identifying = 5;
inline bool CMsgGCHAccountPhoneNumberChange::_internal_has_is_identifying() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool CMsgGCHAccountPhoneNumberChange::has_is_identifying() const {
  return _internal_has_is_identifying();
}
inline void CMsgGCHAccountPhoneNumberChange::clear_is_identifying() {
  _impl_.is_identifying_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool CMsgGCHAccountPhoneNumberChange::_internal_is_identifying() const {
  return _impl_.is_identifying_;
}
inline bool CMsgGCHAccountPhoneNumberChange::is_identifying() const {
  // @@protoc_insertion_point(field_get:CMsgGCHAccountPhoneNumberChange.is_identifying)
  return _internal_is_identifying();
}
inline void CMsgGCHAccountPhoneNumberChange::_internal_set_is_identifying(bool value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.is_identifying_ = value;
}
inline void CMsgGCHAccountPhoneNumberChange::set_is_identifying(bool value) {
  _internal_set_is_identifying(value);
  // @@protoc_insertion_point(field_set:CMsgGCHAccountPhoneNumberChange.is_identifying)
}

// -------------------------------------------------------------------

// CMsgGCHInviteUserToLobby

// optional fixed64 steamid = 1;
inline bool CMsgGCHInviteUserToLobby::_internal_has_steamid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgGCHInviteUserToLobby::has_steamid() const {
  return _internal_has_steamid();
}
inline void CMsgGCHInviteUserToLobby::clear_steamid() {
  _impl_.steamid_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint64_t CMsgGCHInviteUserToLobby::_internal_steamid() const {
  return _impl_.steamid_;
}
inline uint64_t CMsgGCHInviteUserToLobby::steamid() const {
  // @@protoc_insertion_point(field_get:CMsgGCHInviteUserToLobby.steamid)
  return _internal_steamid();
}
inline void CMsgGCHInviteUserToLobby::_internal_set_steamid(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.steamid_ = value;
}
inline void CMsgGCHInviteUserToLobby::set_steamid(uint64_t value) {
  _internal_set_steamid(value);
  // @@protoc_insertion_point(field_set:CMsgGCHInviteUserToLobby.steamid)
}

// optional uint32 appid = 2;
inline bool CMsgGCHInviteUserToLobby::_internal_has_appid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CMsgGCHInviteUserToLobby::has_appid() const {
  return _internal_has_appid();
}
inline void CMsgGCHInviteUserToLobby::clear_appid() {
  _impl_.appid_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t CMsgGCHInviteUserToLobby::_internal_appid() const {
  return _impl_.appid_;
}
inline uint32_t CMsgGCHInviteUserToLobby::appid() const {
  // @@protoc_insertion_point(field_get:CMsgGCHInviteUserToLobby.appid)
  return _internal_appid();
}
inline void CMsgGCHInviteUserToLobby::_internal_set_appid(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.appid_ = value;
}
inline void CMsgGCHInviteUserToLobby::set_appid(uint32_t value) {
  _internal_set_appid(value);
  // @@protoc_insertion_point(field_set:CMsgGCHInviteUserToLobby.appid)
}

// optional fixed64 steamid_invited = 3;
inline bool CMsgGCHInviteUserToLobby::_internal_has_steamid_invited() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgGCHInviteUserToLobby::has_steamid_invited() const {
  return _internal_has_steamid_invited();
}
inline void CMsgGCHInviteUserToLobby::clear_steamid_invited() {
  _impl_.steamid_invited_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint64_t CMsgGCHInviteUserToLobby::_internal_steamid_invited() const {
  return _impl_.steamid_invited_;
}
inline uint64_t CMsgGCHInviteUserToLobby::steamid_invited() const {
  // @@protoc_insertion_point(field_get:CMsgGCHInviteUserToLobby.steamid_invited)
  return _internal_steamid_invited();
}
inline void CMsgGCHInviteUserToLobby::_internal_set_steamid_invited(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.steamid_invited_ = value;
}
inline void CMsgGCHInviteUserToLobby::set_steamid_invited(uint64_t value) {
  _internal_set_steamid_invited(value);
  // @@protoc_insertion_point(field_set:CMsgGCHInviteUserToLobby.steamid_invited)
}

// optional fixed64 steamid_lobby = 4;
inline bool CMsgGCHInviteUserToLobby::_internal_has_steamid_lobby() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CMsgGCHInviteUserToLobby::has_steamid_lobby() const {
  return _internal_has_steamid_lobby();
}
inline void CMsgGCHInviteUserToLobby::clear_steamid_lobby() {
  _impl_.steamid_lobby_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint64_t CMsgGCHInviteUserToLobby::_internal_steamid_lobby() const {
  return _impl_.steamid_lobby_;
}
inline uint64_t CMsgGCHInviteUserToLobby::steamid_lobby() const {
  // @@protoc_insertion_point(field_get:CMsgGCHInviteUserToLobby.steamid_lobby)
  return _internal_steamid_lobby();
}
inline void CMsgGCHInviteUserToLobby::_internal_set_steamid_lobby(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.steamid_lobby_ = value;
}
inline void CMsgGCHInviteUserToLobby::set_steamid_lobby(uint64_t value) {
  _internal_set_steamid_lobby(value);
  // @@protoc_insertion_point(field_set:CMsgGCHInviteUserToLobby.steamid_lobby)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::EGCSystemMsg> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EGCSystemMsg>() {
  return ::EGCSystemMsg_descriptor();
}
template <> struct is_proto_enum< ::ESOMsg> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ESOMsg>() {
  return ::ESOMsg_descriptor();
}
template <> struct is_proto_enum< ::EGCBaseClientMsg> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EGCBaseClientMsg>() {
  return ::EGCBaseClientMsg_descriptor();
}
template <> struct is_proto_enum< ::EGCToGCMsg> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EGCToGCMsg>() {
  return ::EGCToGCMsg_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_gcsystemmsgs_2eproto
