// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gcsystemmsgs.proto

#include "gcsystemmsgs.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR CMsgGCHVacVerificationChange::CMsgGCHVacVerificationChange(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.steamid_)*/uint64_t{0u}
  , /*decltype(_impl_.appid_)*/0u
  , /*decltype(_impl_.is_verified_)*/false} {}
struct CMsgGCHVacVerificationChangeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgGCHVacVerificationChangeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCHVacVerificationChangeDefaultTypeInternal() {}
  union {
    CMsgGCHVacVerificationChange _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCHVacVerificationChangeDefaultTypeInternal _CMsgGCHVacVerificationChange_default_instance_;
PROTOBUF_CONSTEXPR CMsgGCHAccountPhoneNumberChange::CMsgGCHAccountPhoneNumberChange(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.steamid_)*/uint64_t{0u}
  , /*decltype(_impl_.phone_id_)*/uint64_t{0u}
  , /*decltype(_impl_.appid_)*/0u
  , /*decltype(_impl_.is_verified_)*/false
  , /*decltype(_impl_.is_identifying_)*/false} {}
struct CMsgGCHAccountPhoneNumberChangeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgGCHAccountPhoneNumberChangeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCHAccountPhoneNumberChangeDefaultTypeInternal() {}
  union {
    CMsgGCHAccountPhoneNumberChange _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCHAccountPhoneNumberChangeDefaultTypeInternal _CMsgGCHAccountPhoneNumberChange_default_instance_;
PROTOBUF_CONSTEXPR CMsgGCHInviteUserToLobby::CMsgGCHInviteUserToLobby(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.steamid_)*/uint64_t{0u}
  , /*decltype(_impl_.steamid_invited_)*/uint64_t{0u}
  , /*decltype(_impl_.steamid_lobby_)*/uint64_t{0u}
  , /*decltype(_impl_.appid_)*/0u} {}
struct CMsgGCHInviteUserToLobbyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgGCHInviteUserToLobbyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCHInviteUserToLobbyDefaultTypeInternal() {}
  union {
    CMsgGCHInviteUserToLobby _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCHInviteUserToLobbyDefaultTypeInternal _CMsgGCHInviteUserToLobby_default_instance_;
static ::_pb::Metadata file_level_metadata_gcsystemmsgs_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_gcsystemmsgs_2eproto[4];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_gcsystemmsgs_2eproto = nullptr;

const uint32_t TableStruct_gcsystemmsgs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::CMsgGCHVacVerificationChange, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHVacVerificationChange, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgGCHVacVerificationChange, _impl_.steamid_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHVacVerificationChange, _impl_.appid_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHVacVerificationChange, _impl_.is_verified_),
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::CMsgGCHAccountPhoneNumberChange, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHAccountPhoneNumberChange, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgGCHAccountPhoneNumberChange, _impl_.steamid_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHAccountPhoneNumberChange, _impl_.appid_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHAccountPhoneNumberChange, _impl_.phone_id_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHAccountPhoneNumberChange, _impl_.is_verified_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHAccountPhoneNumberChange, _impl_.is_identifying_),
  0,
  2,
  1,
  3,
  4,
  PROTOBUF_FIELD_OFFSET(::CMsgGCHInviteUserToLobby, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHInviteUserToLobby, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgGCHInviteUserToLobby, _impl_.steamid_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHInviteUserToLobby, _impl_.appid_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHInviteUserToLobby, _impl_.steamid_invited_),
  PROTOBUF_FIELD_OFFSET(::CMsgGCHInviteUserToLobby, _impl_.steamid_lobby_),
  0,
  3,
  1,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::CMsgGCHVacVerificationChange)},
  { 12, 23, -1, sizeof(::CMsgGCHAccountPhoneNumberChange)},
  { 28, 38, -1, sizeof(::CMsgGCHInviteUserToLobby)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_CMsgGCHVacVerificationChange_default_instance_._instance,
  &::_CMsgGCHAccountPhoneNumberChange_default_instance_._instance,
  &::_CMsgGCHInviteUserToLobby_default_instance_._instance,
};

const char descriptor_table_protodef_gcsystemmsgs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022gcsystemmsgs.proto\"S\n\034CMsgGCHVacVerifi"
  "cationChange\022\017\n\007steamid\030\001 \001(\006\022\r\n\005appid\030\002"
  " \001(\r\022\023\n\013is_verified\030\003 \001(\010\"\200\001\n\037CMsgGCHAcc"
  "ountPhoneNumberChange\022\017\n\007steamid\030\001 \001(\006\022\r"
  "\n\005appid\030\002 \001(\r\022\020\n\010phone_id\030\003 \001(\004\022\023\n\013is_ve"
  "rified\030\004 \001(\010\022\026\n\016is_identifying\030\005 \001(\010\"j\n\030"
  "CMsgGCHInviteUserToLobby\022\017\n\007steamid\030\001 \001("
  "\006\022\r\n\005appid\030\002 \001(\r\022\027\n\017steamid_invited\030\003 \001("
  "\006\022\025\n\rsteamid_lobby\030\004 \001(\006*\307\024\n\014EGCSystemMs"
  "g\022\023\n\017k_EGCMsgInvalid\020\000\022\021\n\rk_EGCMsgMulti\020"
  "\001\022\030\n\024k_EGCMsgGenericReply\020\n\022\026\n\022k_EGCMsgS"
  "ystemBase\0202\022\036\n\032k_EGCMsgAchievementAwarde"
  "d\0203\022\026\n\022k_EGCMsgConCommand\0204\022\030\n\024k_EGCMsgS"
  "tartPlaying\0205\022\027\n\023k_EGCMsgStopPlaying\0206\022\033"
  "\n\027k_EGCMsgStartGameserver\0207\022\032\n\026k_EGCMsgS"
  "topGameserver\0208\022\025\n\021k_EGCMsgWGRequest\0209\022\026"
  "\n\022k_EGCMsgWGResponse\020:\022\"\n\036k_EGCMsgGetUse"
  "rGameStatsSchema\020;\022*\n&k_EGCMsgGetUserGam"
  "eStatsSchemaResponse\020<\022\"\n\036k_EGCMsgGetUse"
  "rStatsDEPRECATED\020=\022 \n\034k_EGCMsgGetUserSta"
  "tsResponse\020>\022\032\n\026k_EGCMsgAppInfoUpdated\020\?"
  "\022\033\n\027k_EGCMsgValidateSession\020@\022#\n\037k_EGCMs"
  "gValidateSessionResponse\020A\022\"\n\036k_EGCMsgLo"
  "okupAccountFromInput\020B\022\033\n\027k_EGCMsgSendHT"
  "TPRequest\020C\022#\n\037k_EGCMsgSendHTTPRequestRe"
  "sponse\020D\022\030\n\024k_EGCMsgPreTestSetup\020E\022\037\n\033k_"
  "EGCMsgRecordSupportAction\020F\022(\n$k_EGCMsgG"
  "etAccountDetails_DEPRECATED\020G\022\"\n\036k_EGCMs"
  "gReceiveInterAppMessage\020I\022\030\n\024k_EGCMsgFin"
  "dAccounts\020J\022\025\n\021k_EGCMsgPostAlert\020K\022\027\n\023k_"
  "EGCMsgGetLicenses\020L\022\030\n\024k_EGCMsgGetUserSt"
  "ats\020M\022\027\n\023k_EGCMsgGetCommands\020N\022\037\n\033k_EGCM"
  "sgGetCommandsResponse\020O\022\032\n\026k_EGCMsgAddFr"
  "eeLicense\020P\022\"\n\036k_EGCMsgAddFreeLicenseRes"
  "ponse\020Q\022\031\n\025k_EGCMsgGetIPLocation\020R\022!\n\035k_"
  "EGCMsgGetIPLocationResponse\020S\022\035\n\031k_EGCMs"
  "gSystemStatsSchema\020T\022\032\n\026k_EGCMsgGetSyste"
  "mStats\020U\022\"\n\036k_EGCMsgGetSystemStatsRespon"
  "se\020V\022\025\n\021k_EGCMsgSendEmail\020W\022\035\n\031k_EGCMsgS"
  "endEmailResponse\020X\022\034\n\030k_EGCMsgGetEmailTe"
  "mplate\020Y\022$\n k_EGCMsgGetEmailTemplateResp"
  "onse\020Z\022\032\n\026k_EGCMsgGrantGuestPass\020[\022\"\n\036k_"
  "EGCMsgGrantGuestPassResponse\020\\\022\035\n\031k_EGCM"
  "sgGetAccountDetails\020]\022%\n!k_EGCMsgGetAcco"
  "untDetailsResponse\020^\022\033\n\027k_EGCMsgGetPerso"
  "naNames\020_\022#\n\037k_EGCMsgGetPersonaNamesResp"
  "onse\020`\022\030\n\024k_EGCMsgMultiplexMsg\020a\022 \n\034k_EG"
  "CMsgMultiplexMsgResponse\020b\022$\n k_EGCMsgWe"
  "bAPIRegisterInterfaces\020e\022\034\n\030k_EGCMsgWebA"
  "PIJobRequest\020f\022(\n$k_EGCMsgWebAPIJobReque"
  "stHttpResponse\020h\022+\n\'k_EGCMsgWebAPIJobReq"
  "uestForwardResponse\020i\022\031\n\024k_EGCMsgMemCach"
  "edGet\020\310\001\022!\n\034k_EGCMsgMemCachedGetResponse"
  "\020\311\001\022\031\n\024k_EGCMsgMemCachedSet\020\312\001\022\034\n\027k_EGCM"
  "sgMemCachedDelete\020\313\001\022\033\n\026k_EGCMsgMemCache"
  "dStats\020\314\001\022#\n\036k_EGCMsgMemCachedStatsRespo"
  "nse\020\315\001\022\037\n\032k_EGCMsgMasterSetDirectory\020\334\001\022"
  "\'\n\"k_EGCMsgMasterSetDirectoryResponse\020\335\001"
  "\022#\n\036k_EGCMsgMasterSetWebAPIRouting\020\336\001\022+\n"
  "&k_EGCMsgMasterSetWebAPIRoutingResponse\020"
  "\337\001\022&\n!k_EGCMsgMasterSetClientMsgRouting\020"
  "\340\001\022.\n)k_EGCMsgMasterSetClientMsgRoutingR"
  "esponse\020\341\001\022\027\n\022k_EGCMsgSetOptions\020\342\001\022\037\n\032k"
  "_EGCMsgSetOptionsResponse\020\343\001\022\030\n\023k_EGCMsg"
  "SystemBase2\020\364\003\022#\n\036k_EGCMsgGetPurchaseTru"
  "stStatus\020\365\003\022+\n&k_EGCMsgGetPurchaseTrustS"
  "tatusResponse\020\366\003\022\032\n\025k_EGCMsgUpdateSessio"
  "n\020\367\003\022%\n k_EGCMsgGCAccountVacStatusChange"
  "\020\370\003\022\034\n\027k_EGCMsgCheckFriendship\020\371\003\022$\n\037k_E"
  "GCMsgCheckFriendshipResponse\020\372\003\022\"\n\035k_EGC"
  "MsgGetPartnerAccountLink\020\373\003\022*\n%k_EGCMsgG"
  "etPartnerAccountLinkResponse\020\374\003\022\"\n\035k_EGC"
  "MsgVacVerificationChange\020\206\004\022%\n k_EGCMsgA"
  "ccountPhoneNumberChange\020\207\004\022\036\n\031k_EGCMsgIn"
  "viteUserToLobby\020\213\004*\357\001\n\006ESOMsg\022\023\n\017k_ESOMs"
  "g_Create\020\025\022\023\n\017k_ESOMsg_Update\020\026\022\024\n\020k_ESO"
  "Msg_Destroy\020\027\022\034\n\030k_ESOMsg_CacheSubscribe"
  "d\020\030\022\036\n\032k_ESOMsg_CacheUnsubscribed\020\031\022\033\n\027k"
  "_ESOMsg_UpdateMultiple\020\032\022#\n\037k_ESOMsg_Cac"
  "heSubscriptionCheck\020\033\022%\n!k_ESOMsg_CacheS"
  "ubscriptionRefresh\020\034*\331\002\n\020EGCBaseClientMs"
  "g\022\032\n\025k_EMsgGCClientWelcome\020\244\037\022\032\n\025k_EMsgG"
  "CServerWelcome\020\245\037\022\030\n\023k_EMsgGCClientHello"
  "\020\246\037\022\030\n\023k_EMsgGCServerHello\020\247\037\022#\n\036k_EMsgG"
  "CClientConnectionStatus\020\251\037\022#\n\036k_EMsgGCSe"
  "rverConnectionStatus\020\252\037\022\037\n\032k_EMsgGCClien"
  "tHelloPartner\020\253\037\022\032\n\025k_EMsgGCClientHelloP"
  "W\020\254\037\022\032\n\025k_EMsgGCClientHelloR2\020\255\037\022\032\n\025k_EM"
  "sgGCClientHelloR3\020\256\037\022\032\n\025k_EMsgGCClientHe"
  "lloR4\020\257\037*\211\002\n\nEGCToGCMsg\022\032\n\025k_EGCToGCMsgM"
  "asterAck\020\226\001\022\"\n\035k_EGCToGCMsgMasterAckResp"
  "onse\020\227\001\022\027\n\022k_EGCToGCMsgRouted\020\230\001\022\034\n\027k_EG"
  "CToGCMsgRoutedReply\020\231\001\022\032\n\025k_EMsgUpdateSe"
  "ssionIP\020\232\001\022\033\n\026k_EMsgRequestSessionIP\020\233\001\022"
  "#\n\036k_EMsgRequestSessionIPResponse\020\234\001\022&\n!"
  "k_EGCToGCMsgMasterStartupComplete\020\235\001B\005H\001"
  "\200\001\000"
  ;
static ::_pbi::once_flag descriptor_table_gcsystemmsgs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_gcsystemmsgs_2eproto = {
    false, false, 3843, descriptor_table_protodef_gcsystemmsgs_2eproto,
    "gcsystemmsgs.proto",
    &descriptor_table_gcsystemmsgs_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_gcsystemmsgs_2eproto::offsets,
    file_level_metadata_gcsystemmsgs_2eproto, file_level_enum_descriptors_gcsystemmsgs_2eproto,
    file_level_service_descriptors_gcsystemmsgs_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_gcsystemmsgs_2eproto_getter() {
  return &descriptor_table_gcsystemmsgs_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_gcsystemmsgs_2eproto(&descriptor_table_gcsystemmsgs_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCSystemMsg_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gcsystemmsgs_2eproto);
  return file_level_enum_descriptors_gcsystemmsgs_2eproto[0];
}
bool EGCSystemMsg_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 10:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 70:
    case 71:
    case 73:
    case 74:
    case 75:
    case 76:
    case 77:
    case 78:
    case 79:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 86:
    case 87:
    case 88:
    case 89:
    case 90:
    case 91:
    case 92:
    case 93:
    case 94:
    case 95:
    case 96:
    case 97:
    case 98:
    case 101:
    case 102:
    case 104:
    case 105:
    case 200:
    case 201:
    case 202:
    case 203:
    case 204:
    case 205:
    case 220:
    case 221:
    case 222:
    case 223:
    case 224:
    case 225:
    case 226:
    case 227:
    case 500:
    case 501:
    case 502:
    case 503:
    case 504:
    case 505:
    case 506:
    case 507:
    case 508:
    case 518:
    case 519:
    case 523:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESOMsg_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gcsystemmsgs_2eproto);
  return file_level_enum_descriptors_gcsystemmsgs_2eproto[1];
}
bool ESOMsg_IsValid(int value) {
  switch (value) {
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCBaseClientMsg_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gcsystemmsgs_2eproto);
  return file_level_enum_descriptors_gcsystemmsgs_2eproto[2];
}
bool EGCBaseClientMsg_IsValid(int value) {
  switch (value) {
    case 4004:
    case 4005:
    case 4006:
    case 4007:
    case 4009:
    case 4010:
    case 4011:
    case 4012:
    case 4013:
    case 4014:
    case 4015:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCToGCMsg_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gcsystemmsgs_2eproto);
  return file_level_enum_descriptors_gcsystemmsgs_2eproto[3];
}
bool EGCToGCMsg_IsValid(int value) {
  switch (value) {
    case 150:
    case 151:
    case 152:
    case 153:
    case 154:
    case 155:
    case 156:
    case 157:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class CMsgGCHVacVerificationChange::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgGCHVacVerificationChange>()._impl_._has_bits_);
  static void set_has_steamid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_appid(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_is_verified(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

CMsgGCHVacVerificationChange::CMsgGCHVacVerificationChange(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgGCHVacVerificationChange)
}
CMsgGCHVacVerificationChange::CMsgGCHVacVerificationChange(const CMsgGCHVacVerificationChange& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgGCHVacVerificationChange* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.steamid_){}
    , decltype(_impl_.appid_){}
    , decltype(_impl_.is_verified_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.steamid_, &from._impl_.steamid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_verified_) -
    reinterpret_cast<char*>(&_impl_.steamid_)) + sizeof(_impl_.is_verified_));
  // @@protoc_insertion_point(copy_constructor:CMsgGCHVacVerificationChange)
}

inline void CMsgGCHVacVerificationChange::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.steamid_){uint64_t{0u}}
    , decltype(_impl_.appid_){0u}
    , decltype(_impl_.is_verified_){false}
  };
}

CMsgGCHVacVerificationChange::~CMsgGCHVacVerificationChange() {
  // @@protoc_insertion_point(destructor:CMsgGCHVacVerificationChange)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgGCHVacVerificationChange::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgGCHVacVerificationChange::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgGCHVacVerificationChange::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCHVacVerificationChange)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.steamid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.is_verified_) -
        reinterpret_cast<char*>(&_impl_.steamid_)) + sizeof(_impl_.is_verified_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgGCHVacVerificationChange::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional fixed64 steamid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _Internal::set_has_steamid(&has_bits);
          _impl_.steamid_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 appid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_appid(&has_bits);
          _impl_.appid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool is_verified = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_is_verified(&has_bits);
          _impl_.is_verified_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgGCHVacVerificationChange::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCHVacVerificationChange)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional fixed64 steamid = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(1, this->_internal_steamid(), target);
  }

  // optional uint32 appid = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_appid(), target);
  }

  // optional bool is_verified = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_is_verified(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCHVacVerificationChange)
  return target;
}

size_t CMsgGCHVacVerificationChange::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgGCHVacVerificationChange)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional fixed64 steamid = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 8;
    }

    // optional uint32 appid = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_appid());
    }

    // optional bool is_verified = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgGCHVacVerificationChange::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgGCHVacVerificationChange::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgGCHVacVerificationChange::GetClassData() const { return &_class_data_; }


void CMsgGCHVacVerificationChange::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgGCHVacVerificationChange*>(&to_msg);
  auto& from = static_cast<const CMsgGCHVacVerificationChange&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCHVacVerificationChange)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.steamid_ = from._impl_.steamid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.appid_ = from._impl_.appid_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.is_verified_ = from._impl_.is_verified_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgGCHVacVerificationChange::CopyFrom(const CMsgGCHVacVerificationChange& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCHVacVerificationChange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgGCHVacVerificationChange::IsInitialized() const {
  return true;
}

void CMsgGCHVacVerificationChange::InternalSwap(CMsgGCHVacVerificationChange* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgGCHVacVerificationChange, _impl_.is_verified_)
      + sizeof(CMsgGCHVacVerificationChange::_impl_.is_verified_)
      - PROTOBUF_FIELD_OFFSET(CMsgGCHVacVerificationChange, _impl_.steamid_)>(
          reinterpret_cast<char*>(&_impl_.steamid_),
          reinterpret_cast<char*>(&other->_impl_.steamid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgGCHVacVerificationChange::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gcsystemmsgs_2eproto_getter, &descriptor_table_gcsystemmsgs_2eproto_once,
      file_level_metadata_gcsystemmsgs_2eproto[0]);
}

// ===================================================================

class CMsgGCHAccountPhoneNumberChange::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgGCHAccountPhoneNumberChange>()._impl_._has_bits_);
  static void set_has_steamid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_appid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_phone_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_is_verified(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_is_identifying(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

CMsgGCHAccountPhoneNumberChange::CMsgGCHAccountPhoneNumberChange(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgGCHAccountPhoneNumberChange)
}
CMsgGCHAccountPhoneNumberChange::CMsgGCHAccountPhoneNumberChange(const CMsgGCHAccountPhoneNumberChange& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgGCHAccountPhoneNumberChange* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.steamid_){}
    , decltype(_impl_.phone_id_){}
    , decltype(_impl_.appid_){}
    , decltype(_impl_.is_verified_){}
    , decltype(_impl_.is_identifying_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.steamid_, &from._impl_.steamid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_identifying_) -
    reinterpret_cast<char*>(&_impl_.steamid_)) + sizeof(_impl_.is_identifying_));
  // @@protoc_insertion_point(copy_constructor:CMsgGCHAccountPhoneNumberChange)
}

inline void CMsgGCHAccountPhoneNumberChange::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.steamid_){uint64_t{0u}}
    , decltype(_impl_.phone_id_){uint64_t{0u}}
    , decltype(_impl_.appid_){0u}
    , decltype(_impl_.is_verified_){false}
    , decltype(_impl_.is_identifying_){false}
  };
}

CMsgGCHAccountPhoneNumberChange::~CMsgGCHAccountPhoneNumberChange() {
  // @@protoc_insertion_point(destructor:CMsgGCHAccountPhoneNumberChange)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgGCHAccountPhoneNumberChange::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgGCHAccountPhoneNumberChange::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgGCHAccountPhoneNumberChange::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCHAccountPhoneNumberChange)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    ::memset(&_impl_.steamid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.is_identifying_) -
        reinterpret_cast<char*>(&_impl_.steamid_)) + sizeof(_impl_.is_identifying_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgGCHAccountPhoneNumberChange::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional fixed64 steamid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _Internal::set_has_steamid(&has_bits);
          _impl_.steamid_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 appid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_appid(&has_bits);
          _impl_.appid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 phone_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_phone_id(&has_bits);
          _impl_.phone_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool is_verified = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_is_verified(&has_bits);
          _impl_.is_verified_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool is_identifying = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_is_identifying(&has_bits);
          _impl_.is_identifying_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgGCHAccountPhoneNumberChange::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCHAccountPhoneNumberChange)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional fixed64 steamid = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(1, this->_internal_steamid(), target);
  }

  // optional uint32 appid = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_appid(), target);
  }

  // optional uint64 phone_id = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_phone_id(), target);
  }

  // optional bool is_verified = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_is_verified(), target);
  }

  // optional bool is_identifying = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_is_identifying(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCHAccountPhoneNumberChange)
  return target;
}

size_t CMsgGCHAccountPhoneNumberChange::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgGCHAccountPhoneNumberChange)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional fixed64 steamid = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 8;
    }

    // optional uint64 phone_id = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_phone_id());
    }

    // optional uint32 appid = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_appid());
    }

    // optional bool is_verified = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional bool is_identifying = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 1;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgGCHAccountPhoneNumberChange::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgGCHAccountPhoneNumberChange::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgGCHAccountPhoneNumberChange::GetClassData() const { return &_class_data_; }


void CMsgGCHAccountPhoneNumberChange::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgGCHAccountPhoneNumberChange*>(&to_msg);
  auto& from = static_cast<const CMsgGCHAccountPhoneNumberChange&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCHAccountPhoneNumberChange)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.steamid_ = from._impl_.steamid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.phone_id_ = from._impl_.phone_id_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.appid_ = from._impl_.appid_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.is_verified_ = from._impl_.is_verified_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.is_identifying_ = from._impl_.is_identifying_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgGCHAccountPhoneNumberChange::CopyFrom(const CMsgGCHAccountPhoneNumberChange& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCHAccountPhoneNumberChange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgGCHAccountPhoneNumberChange::IsInitialized() const {
  return true;
}

void CMsgGCHAccountPhoneNumberChange::InternalSwap(CMsgGCHAccountPhoneNumberChange* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgGCHAccountPhoneNumberChange, _impl_.is_identifying_)
      + sizeof(CMsgGCHAccountPhoneNumberChange::_impl_.is_identifying_)
      - PROTOBUF_FIELD_OFFSET(CMsgGCHAccountPhoneNumberChange, _impl_.steamid_)>(
          reinterpret_cast<char*>(&_impl_.steamid_),
          reinterpret_cast<char*>(&other->_impl_.steamid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgGCHAccountPhoneNumberChange::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gcsystemmsgs_2eproto_getter, &descriptor_table_gcsystemmsgs_2eproto_once,
      file_level_metadata_gcsystemmsgs_2eproto[1]);
}

// ===================================================================

class CMsgGCHInviteUserToLobby::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgGCHInviteUserToLobby>()._impl_._has_bits_);
  static void set_has_steamid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_appid(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_steamid_invited(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_steamid_lobby(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

CMsgGCHInviteUserToLobby::CMsgGCHInviteUserToLobby(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgGCHInviteUserToLobby)
}
CMsgGCHInviteUserToLobby::CMsgGCHInviteUserToLobby(const CMsgGCHInviteUserToLobby& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgGCHInviteUserToLobby* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.steamid_){}
    , decltype(_impl_.steamid_invited_){}
    , decltype(_impl_.steamid_lobby_){}
    , decltype(_impl_.appid_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.steamid_, &from._impl_.steamid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.appid_) -
    reinterpret_cast<char*>(&_impl_.steamid_)) + sizeof(_impl_.appid_));
  // @@protoc_insertion_point(copy_constructor:CMsgGCHInviteUserToLobby)
}

inline void CMsgGCHInviteUserToLobby::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.steamid_){uint64_t{0u}}
    , decltype(_impl_.steamid_invited_){uint64_t{0u}}
    , decltype(_impl_.steamid_lobby_){uint64_t{0u}}
    , decltype(_impl_.appid_){0u}
  };
}

CMsgGCHInviteUserToLobby::~CMsgGCHInviteUserToLobby() {
  // @@protoc_insertion_point(destructor:CMsgGCHInviteUserToLobby)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgGCHInviteUserToLobby::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgGCHInviteUserToLobby::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgGCHInviteUserToLobby::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCHInviteUserToLobby)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&_impl_.steamid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.appid_) -
        reinterpret_cast<char*>(&_impl_.steamid_)) + sizeof(_impl_.appid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgGCHInviteUserToLobby::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional fixed64 steamid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _Internal::set_has_steamid(&has_bits);
          _impl_.steamid_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 appid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_appid(&has_bits);
          _impl_.appid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional fixed64 steamid_invited = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _Internal::set_has_steamid_invited(&has_bits);
          _impl_.steamid_invited_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // optional fixed64 steamid_lobby = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _Internal::set_has_steamid_lobby(&has_bits);
          _impl_.steamid_lobby_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgGCHInviteUserToLobby::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCHInviteUserToLobby)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional fixed64 steamid = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(1, this->_internal_steamid(), target);
  }

  // optional uint32 appid = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_appid(), target);
  }

  // optional fixed64 steamid_invited = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(3, this->_internal_steamid_invited(), target);
  }

  // optional fixed64 steamid_lobby = 4;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(4, this->_internal_steamid_lobby(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCHInviteUserToLobby)
  return target;
}

size_t CMsgGCHInviteUserToLobby::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgGCHInviteUserToLobby)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional fixed64 steamid = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 8;
    }

    // optional fixed64 steamid_invited = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 8;
    }

    // optional fixed64 steamid_lobby = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

    // optional uint32 appid = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_appid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgGCHInviteUserToLobby::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgGCHInviteUserToLobby::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgGCHInviteUserToLobby::GetClassData() const { return &_class_data_; }


void CMsgGCHInviteUserToLobby::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgGCHInviteUserToLobby*>(&to_msg);
  auto& from = static_cast<const CMsgGCHInviteUserToLobby&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCHInviteUserToLobby)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.steamid_ = from._impl_.steamid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.steamid_invited_ = from._impl_.steamid_invited_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.steamid_lobby_ = from._impl_.steamid_lobby_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.appid_ = from._impl_.appid_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgGCHInviteUserToLobby::CopyFrom(const CMsgGCHInviteUserToLobby& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCHInviteUserToLobby)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgGCHInviteUserToLobby::IsInitialized() const {
  return true;
}

void CMsgGCHInviteUserToLobby::InternalSwap(CMsgGCHInviteUserToLobby* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgGCHInviteUserToLobby, _impl_.appid_)
      + sizeof(CMsgGCHInviteUserToLobby::_impl_.appid_)
      - PROTOBUF_FIELD_OFFSET(CMsgGCHInviteUserToLobby, _impl_.steamid_)>(
          reinterpret_cast<char*>(&_impl_.steamid_),
          reinterpret_cast<char*>(&other->_impl_.steamid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgGCHInviteUserToLobby::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gcsystemmsgs_2eproto_getter, &descriptor_table_gcsystemmsgs_2eproto_once,
      file_level_metadata_gcsystemmsgs_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CMsgGCHVacVerificationChange*
Arena::CreateMaybeMessage< ::CMsgGCHVacVerificationChange >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgGCHVacVerificationChange >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgGCHAccountPhoneNumberChange*
Arena::CreateMaybeMessage< ::CMsgGCHAccountPhoneNumberChange >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgGCHAccountPhoneNumberChange >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgGCHInviteUserToLobby*
Arena::CreateMaybeMessage< ::CMsgGCHInviteUserToLobby >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgGCHInviteUserToLobby >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
