// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: econ_gcmessages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_econ_5fgcmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_econ_5fgcmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "steammessages.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_econ_5fgcmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_econ_5fgcmessages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_econ_5fgcmessages_2eproto;
class CMsgApplyAutograph;
struct CMsgApplyAutographDefaultTypeInternal;
extern CMsgApplyAutographDefaultTypeInternal _CMsgApplyAutograph_default_instance_;
class CMsgGCGiftedItems;
struct CMsgGCGiftedItemsDefaultTypeInternal;
extern CMsgGCGiftedItemsDefaultTypeInternal _CMsgGCGiftedItems_default_instance_;
class CMsgGCUserTrackTimePlayedConsecutively;
struct CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal;
extern CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal _CMsgGCUserTrackTimePlayedConsecutively_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CMsgApplyAutograph* Arena::CreateMaybeMessage<::CMsgApplyAutograph>(Arena*);
template<> ::CMsgGCGiftedItems* Arena::CreateMaybeMessage<::CMsgGCGiftedItems>(Arena*);
template<> ::CMsgGCUserTrackTimePlayedConsecutively* Arena::CreateMaybeMessage<::CMsgGCUserTrackTimePlayedConsecutively>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum EGCItemMsg : int {
  k_EMsgGCBase = 1000,
  k_EMsgGCSetItemPosition = 1001,
  k_EMsgGCCraft = 1002,
  k_EMsgGCCraftResponse = 1003,
  k_EMsgGCDelete = 1004,
  k_EMsgGCVerifyCacheSubscription = 1005,
  k_EMsgGCNameItem = 1006,
  k_EMsgGCUnlockCrate = 1007,
  k_EMsgGCUnlockCrateResponse = 1008,
  k_EMsgGCPaintItem = 1009,
  k_EMsgGCPaintItemResponse = 1010,
  k_EMsgGCGoldenWrenchBroadcast = 1011,
  k_EMsgGCMOTDRequest = 1012,
  k_EMsgGCMOTDRequestResponse = 1013,
  k_EMsgGCAddItemToSocket_DEPRECATED = 1014,
  k_EMsgGCAddItemToSocketResponse_DEPRECATED = 1015,
  k_EMsgGCAddSocketToBaseItem_DEPRECATED = 1016,
  k_EMsgGCAddSocketToItem_DEPRECATED = 1017,
  k_EMsgGCAddSocketToItemResponse_DEPRECATED = 1018,
  k_EMsgGCNameBaseItem = 1019,
  k_EMsgGCNameBaseItemResponse = 1020,
  k_EMsgGCRemoveSocketItem_DEPRECATED = 1021,
  k_EMsgGCRemoveSocketItemResponse_DEPRECATED = 1022,
  k_EMsgGCCustomizeItemTexture = 1023,
  k_EMsgGCCustomizeItemTextureResponse = 1024,
  k_EMsgGCUseItemRequest = 1025,
  k_EMsgGCUseItemResponse = 1026,
  k_EMsgGCGiftedItems_DEPRECATED = 1027,
  k_EMsgGCRemoveItemName = 1030,
  k_EMsgGCRemoveItemPaint = 1031,
  k_EMsgGCGiftWrapItem = 1032,
  k_EMsgGCGiftWrapItemResponse = 1033,
  k_EMsgGCDeliverGift = 1034,
  k_EMsgGCDeliverGiftResponseGiver = 1035,
  k_EMsgGCDeliverGiftResponseReceiver = 1036,
  k_EMsgGCUnwrapGiftRequest = 1037,
  k_EMsgGCUnwrapGiftResponse = 1038,
  k_EMsgGCSetItemStyle = 1039,
  k_EMsgGCUsedClaimCodeItem = 1040,
  k_EMsgGCSortItems = 1041,
  k_EMsgGC_RevolvingLootList_DEPRECATED = 1042,
  k_EMsgGCLookupAccount = 1043,
  k_EMsgGCLookupAccountResponse = 1044,
  k_EMsgGCLookupAccountName = 1045,
  k_EMsgGCLookupAccountNameResponse = 1046,
  k_EMsgGCUpdateItemSchema = 1049,
  k_EMsgGCRemoveCustomTexture = 1051,
  k_EMsgGCRemoveCustomTextureResponse = 1052,
  k_EMsgGCRemoveMakersMark = 1053,
  k_EMsgGCRemoveMakersMarkResponse = 1054,
  k_EMsgGCRemoveUniqueCraftIndex = 1055,
  k_EMsgGCRemoveUniqueCraftIndexResponse = 1056,
  k_EMsgGCSaxxyBroadcast = 1057,
  k_EMsgGCBackpackSortFinished = 1058,
  k_EMsgGCAdjustItemEquippedState = 1059,
  k_EMsgGCCollectItem = 1061,
  k_EMsgGCItemAcknowledged__DEPRECATED = 1062,
  k_EMsgGC_ReportAbuse = 1065,
  k_EMsgGC_ReportAbuseResponse = 1066,
  k_EMsgGCNameItemNotification = 1068,
  k_EMsgGCApplyConsumableEffects = 1069,
  k_EMsgGCConsumableExhausted = 1070,
  k_EMsgGCShowItemsPickedUp = 1071,
  k_EMsgGCClientDisplayNotification = 1072,
  k_EMsgGCApplyStrangePart = 1073,
  k_EMsgGC_IncrementKillCountAttribute = 1074,
  k_EMsgGC_IncrementKillCountResponse = 1075,
  k_EMsgGCApplyPennantUpgrade = 1076,
  k_EMsgGCSetItemPositions = 1077,
  k_EMsgGCApplyEggEssence = 1078,
  k_EMsgGCNameEggEssenceResponse = 1079,
  k_EMsgGCPaintKitItem = 1080,
  k_EMsgGCPaintKitBaseItem = 1081,
  k_EMsgGCPaintKitItemResponse = 1082,
  k_EMsgGCGiftedItems = 1083,
  k_EMsgGCUnlockItemStyle = 1084,
  k_EMsgGCUnlockItemStyleResponse = 1085,
  k_EMsgGCApplySticker = 1086,
  k_EMsgGCItemAcknowledged = 1087,
  k_EMsgGCStatTrakSwap = 1088,
  k_EMsgGCUserTrackTimePlayedConsecutively = 1089,
  k_EMsgGCTradingBase = 1500,
  k_EMsgGCTrading_InitiateTradeRequest = 1501,
  k_EMsgGCTrading_InitiateTradeResponse = 1502,
  k_EMsgGCTrading_StartSession = 1503,
  k_EMsgGCTrading_SetItem = 1504,
  k_EMsgGCTrading_RemoveItem = 1505,
  k_EMsgGCTrading_UpdateTradeInfo = 1506,
  k_EMsgGCTrading_SetReadiness = 1507,
  k_EMsgGCTrading_ReadinessResponse = 1508,
  k_EMsgGCTrading_SessionClosed = 1509,
  k_EMsgGCTrading_CancelSession = 1510,
  k_EMsgGCTrading_TradeChatMsg = 1511,
  k_EMsgGCTrading_ConfirmOffer = 1512,
  k_EMsgGCTrading_TradeTypingChatMsg = 1513,
  k_EMsgGCServerBrowser_FavoriteServer = 1601,
  k_EMsgGCServerBrowser_BlacklistServer = 1602,
  k_EMsgGCServerRentalsBase = 1700,
  k_EMsgGCItemPreviewCheckStatus = 1701,
  k_EMsgGCItemPreviewStatusResponse = 1702,
  k_EMsgGCItemPreviewRequest = 1703,
  k_EMsgGCItemPreviewRequestResponse = 1704,
  k_EMsgGCItemPreviewExpire = 1705,
  k_EMsgGCItemPreviewExpireNotification = 1706,
  k_EMsgGCItemPreviewItemBoughtNotification = 1707,
  k_EMsgGCDev_NewItemRequest = 2001,
  k_EMsgGCDev_NewItemRequestResponse = 2002,
  k_EMsgGCDev_PaintKitDropItem = 2003,
  k_EMsgGCStoreGetUserData = 2500,
  k_EMsgGCStoreGetUserDataResponse = 2501,
  k_EMsgGCStorePurchaseInit_DEPRECATED = 2502,
  k_EMsgGCStorePurchaseInitResponse_DEPRECATED = 2503,
  k_EMsgGCStorePurchaseFinalize = 2504,
  k_EMsgGCStorePurchaseFinalizeResponse = 2505,
  k_EMsgGCStorePurchaseCancel = 2506,
  k_EMsgGCStorePurchaseCancelResponse = 2507,
  k_EMsgGCStorePurchaseQueryTxn = 2508,
  k_EMsgGCStorePurchaseQueryTxnResponse = 2509,
  k_EMsgGCStorePurchaseInit = 2510,
  k_EMsgGCStorePurchaseInitResponse = 2511,
  k_EMsgGCBannedWordListRequest = 2512,
  k_EMsgGCBannedWordListResponse = 2513,
  k_EMsgGCToGCBannedWordListBroadcast = 2514,
  k_EMsgGCToGCBannedWordListUpdated = 2515,
  k_EMsgGCToGCDirtySDOCache = 2516,
  k_EMsgGCToGCDirtyMultipleSDOCache = 2517,
  k_EMsgGCToGCUpdateSQLKeyValue = 2518,
  k_EMsgGCToGCIsTrustedServer = 2519,
  k_EMsgGCToGCIsTrustedServerResponse = 2520,
  k_EMsgGCToGCBroadcastConsoleCommand = 2521,
  k_EMsgGCServerVersionUpdated = 2522,
  k_EMsgGCApplyAutograph = 2523,
  k_EMsgGCToGCWebAPIAccountChanged = 2524,
  k_EMsgGCRequestAnnouncements = 2525,
  k_EMsgGCRequestAnnouncementsResponse = 2526,
  k_EMsgGCRequestPassportItemGrant = 2527,
  k_EMsgGCClientVersionUpdated = 2528
};
bool EGCItemMsg_IsValid(int value);
constexpr EGCItemMsg EGCItemMsg_MIN = k_EMsgGCBase;
constexpr EGCItemMsg EGCItemMsg_MAX = k_EMsgGCClientVersionUpdated;
constexpr int EGCItemMsg_ARRAYSIZE = EGCItemMsg_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCItemMsg_descriptor();
template<typename T>
inline const std::string& EGCItemMsg_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EGCItemMsg>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EGCItemMsg_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EGCItemMsg_descriptor(), enum_t_value);
}
inline bool EGCItemMsg_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EGCItemMsg* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EGCItemMsg>(
    EGCItemMsg_descriptor(), name, value);
}
enum EGCMsgResponse : int {
  k_EGCMsgResponseOK = 0,
  k_EGCMsgResponseDenied = 1,
  k_EGCMsgResponseServerError = 2,
  k_EGCMsgResponseTimeout = 3,
  k_EGCMsgResponseInvalid = 4,
  k_EGCMsgResponseNoMatch = 5,
  k_EGCMsgResponseUnknownError = 6,
  k_EGCMsgResponseNotLoggedOn = 7,
  k_EGCMsgFailedToCreate = 8
};
bool EGCMsgResponse_IsValid(int value);
constexpr EGCMsgResponse EGCMsgResponse_MIN = k_EGCMsgResponseOK;
constexpr EGCMsgResponse EGCMsgResponse_MAX = k_EGCMsgFailedToCreate;
constexpr int EGCMsgResponse_ARRAYSIZE = EGCMsgResponse_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCMsgResponse_descriptor();
template<typename T>
inline const std::string& EGCMsgResponse_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EGCMsgResponse>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EGCMsgResponse_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EGCMsgResponse_descriptor(), enum_t_value);
}
inline bool EGCMsgResponse_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EGCMsgResponse* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EGCMsgResponse>(
    EGCMsgResponse_descriptor(), name, value);
}
enum EUnlockStyle : int {
  k_UnlockStyle_Succeeded = 0,
  k_UnlockStyle_Failed_PreReq = 1,
  k_UnlockStyle_Failed_CantAfford = 2,
  k_UnlockStyle_Failed_CantCommit = 3,
  k_UnlockStyle_Failed_CantLockCache = 4,
  k_UnlockStyle_Failed_CantAffordAttrib = 5
};
bool EUnlockStyle_IsValid(int value);
constexpr EUnlockStyle EUnlockStyle_MIN = k_UnlockStyle_Succeeded;
constexpr EUnlockStyle EUnlockStyle_MAX = k_UnlockStyle_Failed_CantAffordAttrib;
constexpr int EUnlockStyle_ARRAYSIZE = EUnlockStyle_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EUnlockStyle_descriptor();
template<typename T>
inline const std::string& EUnlockStyle_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EUnlockStyle>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EUnlockStyle_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EUnlockStyle_descriptor(), enum_t_value);
}
inline bool EUnlockStyle_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EUnlockStyle* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EUnlockStyle>(
    EUnlockStyle_descriptor(), name, value);
}
// ===================================================================

class CMsgGCGiftedItems final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgGCGiftedItems) */ {
 public:
  inline CMsgGCGiftedItems() : CMsgGCGiftedItems(nullptr) {}
  ~CMsgGCGiftedItems() override;
  explicit PROTOBUF_CONSTEXPR CMsgGCGiftedItems(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgGCGiftedItems(const CMsgGCGiftedItems& from);
  CMsgGCGiftedItems(CMsgGCGiftedItems&& from) noexcept
    : CMsgGCGiftedItems() {
    *this = ::std::move(from);
  }

  inline CMsgGCGiftedItems& operator=(const CMsgGCGiftedItems& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCGiftedItems& operator=(CMsgGCGiftedItems&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgGCGiftedItems& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgGCGiftedItems* internal_default_instance() {
    return reinterpret_cast<const CMsgGCGiftedItems*>(
               &_CMsgGCGiftedItems_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CMsgGCGiftedItems& a, CMsgGCGiftedItems& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgGCGiftedItems* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCGiftedItems* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgGCGiftedItems* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgGCGiftedItems>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgGCGiftedItems& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgGCGiftedItems& from) {
    CMsgGCGiftedItems::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgGCGiftedItems* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgGCGiftedItems";
  }
  protected:
  explicit CMsgGCGiftedItems(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecipientsAccountidsFieldNumber = 5,
    kAccountidFieldNumber = 1,
    kGiftdefindexFieldNumber = 2,
    kMaxGiftsPossibleFieldNumber = 3,
    kNumEligibleRecipientsFieldNumber = 4,
  };
  // repeated uint32 recipients_accountids = 5;
  int recipients_accountids_size() const;
  private:
  int _internal_recipients_accountids_size() const;
  public:
  void clear_recipients_accountids();
  private:
  uint32_t _internal_recipients_accountids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_recipients_accountids() const;
  void _internal_add_recipients_accountids(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_recipients_accountids();
  public:
  uint32_t recipients_accountids(int index) const;
  void set_recipients_accountids(int index, uint32_t value);
  void add_recipients_accountids(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      recipients_accountids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_recipients_accountids();

  // optional uint32 accountid = 1;
  bool has_accountid() const;
  private:
  bool _internal_has_accountid() const;
  public:
  void clear_accountid();
  uint32_t accountid() const;
  void set_accountid(uint32_t value);
  private:
  uint32_t _internal_accountid() const;
  void _internal_set_accountid(uint32_t value);
  public:

  // optional uint32 giftdefindex = 2;
  bool has_giftdefindex() const;
  private:
  bool _internal_has_giftdefindex() const;
  public:
  void clear_giftdefindex();
  uint32_t giftdefindex() const;
  void set_giftdefindex(uint32_t value);
  private:
  uint32_t _internal_giftdefindex() const;
  void _internal_set_giftdefindex(uint32_t value);
  public:

  // optional uint32 max_gifts_possible = 3;
  bool has_max_gifts_possible() const;
  private:
  bool _internal_has_max_gifts_possible() const;
  public:
  void clear_max_gifts_possible();
  uint32_t max_gifts_possible() const;
  void set_max_gifts_possible(uint32_t value);
  private:
  uint32_t _internal_max_gifts_possible() const;
  void _internal_set_max_gifts_possible(uint32_t value);
  public:

  // optional uint32 num_eligible_recipients = 4;
  bool has_num_eligible_recipients() const;
  private:
  bool _internal_has_num_eligible_recipients() const;
  public:
  void clear_num_eligible_recipients();
  uint32_t num_eligible_recipients() const;
  void set_num_eligible_recipients(uint32_t value);
  private:
  uint32_t _internal_num_eligible_recipients() const;
  void _internal_set_num_eligible_recipients(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgGCGiftedItems)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > recipients_accountids_;
    uint32_t accountid_;
    uint32_t giftdefindex_;
    uint32_t max_gifts_possible_;
    uint32_t num_eligible_recipients_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_econ_5fgcmessages_2eproto;
};
// -------------------------------------------------------------------

class CMsgApplyAutograph final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgApplyAutograph) */ {
 public:
  inline CMsgApplyAutograph() : CMsgApplyAutograph(nullptr) {}
  ~CMsgApplyAutograph() override;
  explicit PROTOBUF_CONSTEXPR CMsgApplyAutograph(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgApplyAutograph(const CMsgApplyAutograph& from);
  CMsgApplyAutograph(CMsgApplyAutograph&& from) noexcept
    : CMsgApplyAutograph() {
    *this = ::std::move(from);
  }

  inline CMsgApplyAutograph& operator=(const CMsgApplyAutograph& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgApplyAutograph& operator=(CMsgApplyAutograph&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgApplyAutograph& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgApplyAutograph* internal_default_instance() {
    return reinterpret_cast<const CMsgApplyAutograph*>(
               &_CMsgApplyAutograph_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CMsgApplyAutograph& a, CMsgApplyAutograph& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgApplyAutograph* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgApplyAutograph* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgApplyAutograph* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgApplyAutograph>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgApplyAutograph& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgApplyAutograph& from) {
    CMsgApplyAutograph::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgApplyAutograph* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgApplyAutograph";
  }
  protected:
  explicit CMsgApplyAutograph(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAutographItemIdFieldNumber = 1,
    kItemItemIdFieldNumber = 2,
  };
  // optional uint64 autograph_item_id = 1;
  bool has_autograph_item_id() const;
  private:
  bool _internal_has_autograph_item_id() const;
  public:
  void clear_autograph_item_id();
  uint64_t autograph_item_id() const;
  void set_autograph_item_id(uint64_t value);
  private:
  uint64_t _internal_autograph_item_id() const;
  void _internal_set_autograph_item_id(uint64_t value);
  public:

  // optional uint64 item_item_id = 2;
  bool has_item_item_id() const;
  private:
  bool _internal_has_item_item_id() const;
  public:
  void clear_item_item_id();
  uint64_t item_item_id() const;
  void set_item_item_id(uint64_t value);
  private:
  uint64_t _internal_item_item_id() const;
  void _internal_set_item_item_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgApplyAutograph)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint64_t autograph_item_id_;
    uint64_t item_item_id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_econ_5fgcmessages_2eproto;
};
// -------------------------------------------------------------------

class CMsgGCUserTrackTimePlayedConsecutively final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgGCUserTrackTimePlayedConsecutively) */ {
 public:
  inline CMsgGCUserTrackTimePlayedConsecutively() : CMsgGCUserTrackTimePlayedConsecutively(nullptr) {}
  ~CMsgGCUserTrackTimePlayedConsecutively() override;
  explicit PROTOBUF_CONSTEXPR CMsgGCUserTrackTimePlayedConsecutively(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgGCUserTrackTimePlayedConsecutively(const CMsgGCUserTrackTimePlayedConsecutively& from);
  CMsgGCUserTrackTimePlayedConsecutively(CMsgGCUserTrackTimePlayedConsecutively&& from) noexcept
    : CMsgGCUserTrackTimePlayedConsecutively() {
    *this = ::std::move(from);
  }

  inline CMsgGCUserTrackTimePlayedConsecutively& operator=(const CMsgGCUserTrackTimePlayedConsecutively& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCUserTrackTimePlayedConsecutively& operator=(CMsgGCUserTrackTimePlayedConsecutively&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgGCUserTrackTimePlayedConsecutively& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgGCUserTrackTimePlayedConsecutively* internal_default_instance() {
    return reinterpret_cast<const CMsgGCUserTrackTimePlayedConsecutively*>(
               &_CMsgGCUserTrackTimePlayedConsecutively_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CMsgGCUserTrackTimePlayedConsecutively& a, CMsgGCUserTrackTimePlayedConsecutively& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgGCUserTrackTimePlayedConsecutively* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCUserTrackTimePlayedConsecutively* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgGCUserTrackTimePlayedConsecutively* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgGCUserTrackTimePlayedConsecutively>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgGCUserTrackTimePlayedConsecutively& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgGCUserTrackTimePlayedConsecutively& from) {
    CMsgGCUserTrackTimePlayedConsecutively::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgGCUserTrackTimePlayedConsecutively* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgGCUserTrackTimePlayedConsecutively";
  }
  protected:
  explicit CMsgGCUserTrackTimePlayedConsecutively(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // optional uint32 state = 1;
  bool has_state() const;
  private:
  bool _internal_has_state() const;
  public:
  void clear_state();
  uint32_t state() const;
  void set_state(uint32_t value);
  private:
  uint32_t _internal_state() const;
  void _internal_set_state(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgGCUserTrackTimePlayedConsecutively)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t state_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_econ_5fgcmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CMsgGCGiftedItems

// optional uint32 accountid = 1;
inline bool CMsgGCGiftedItems::_internal_has_accountid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgGCGiftedItems::has_accountid() const {
  return _internal_has_accountid();
}
inline void CMsgGCGiftedItems::clear_accountid() {
  _impl_.accountid_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t CMsgGCGiftedItems::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint32_t CMsgGCGiftedItems::accountid() const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.accountid)
  return _internal_accountid();
}
inline void CMsgGCGiftedItems::_internal_set_accountid(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.accountid_ = value;
}
inline void CMsgGCGiftedItems::set_accountid(uint32_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.accountid)
}

// optional uint32 giftdefindex = 2;
inline bool CMsgGCGiftedItems::_internal_has_giftdefindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgGCGiftedItems::has_giftdefindex() const {
  return _internal_has_giftdefindex();
}
inline void CMsgGCGiftedItems::clear_giftdefindex() {
  _impl_.giftdefindex_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t CMsgGCGiftedItems::_internal_giftdefindex() const {
  return _impl_.giftdefindex_;
}
inline uint32_t CMsgGCGiftedItems::giftdefindex() const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.giftdefindex)
  return _internal_giftdefindex();
}
inline void CMsgGCGiftedItems::_internal_set_giftdefindex(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.giftdefindex_ = value;
}
inline void CMsgGCGiftedItems::set_giftdefindex(uint32_t value) {
  _internal_set_giftdefindex(value);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.giftdefindex)
}

// optional uint32 max_gifts_possible = 3;
inline bool CMsgGCGiftedItems::_internal_has_max_gifts_possible() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CMsgGCGiftedItems::has_max_gifts_possible() const {
  return _internal_has_max_gifts_possible();
}
inline void CMsgGCGiftedItems::clear_max_gifts_possible() {
  _impl_.max_gifts_possible_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t CMsgGCGiftedItems::_internal_max_gifts_possible() const {
  return _impl_.max_gifts_possible_;
}
inline uint32_t CMsgGCGiftedItems::max_gifts_possible() const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.max_gifts_possible)
  return _internal_max_gifts_possible();
}
inline void CMsgGCGiftedItems::_internal_set_max_gifts_possible(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.max_gifts_possible_ = value;
}
inline void CMsgGCGiftedItems::set_max_gifts_possible(uint32_t value) {
  _internal_set_max_gifts_possible(value);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.max_gifts_possible)
}

// optional uint32 num_eligible_recipients = 4;
inline bool CMsgGCGiftedItems::_internal_has_num_eligible_recipients() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CMsgGCGiftedItems::has_num_eligible_recipients() const {
  return _internal_has_num_eligible_recipients();
}
inline void CMsgGCGiftedItems::clear_num_eligible_recipients() {
  _impl_.num_eligible_recipients_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t CMsgGCGiftedItems::_internal_num_eligible_recipients() const {
  return _impl_.num_eligible_recipients_;
}
inline uint32_t CMsgGCGiftedItems::num_eligible_recipients() const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.num_eligible_recipients)
  return _internal_num_eligible_recipients();
}
inline void CMsgGCGiftedItems::_internal_set_num_eligible_recipients(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.num_eligible_recipients_ = value;
}
inline void CMsgGCGiftedItems::set_num_eligible_recipients(uint32_t value) {
  _internal_set_num_eligible_recipients(value);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.num_eligible_recipients)
}

// repeated uint32 recipients_accountids = 5;
inline int CMsgGCGiftedItems::_internal_recipients_accountids_size() const {
  return _impl_.recipients_accountids_.size();
}
inline int CMsgGCGiftedItems::recipients_accountids_size() const {
  return _internal_recipients_accountids_size();
}
inline void CMsgGCGiftedItems::clear_recipients_accountids() {
  _impl_.recipients_accountids_.Clear();
}
inline uint32_t CMsgGCGiftedItems::_internal_recipients_accountids(int index) const {
  return _impl_.recipients_accountids_.Get(index);
}
inline uint32_t CMsgGCGiftedItems::recipients_accountids(int index) const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.recipients_accountids)
  return _internal_recipients_accountids(index);
}
inline void CMsgGCGiftedItems::set_recipients_accountids(int index, uint32_t value) {
  _impl_.recipients_accountids_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.recipients_accountids)
}
inline void CMsgGCGiftedItems::_internal_add_recipients_accountids(uint32_t value) {
  _impl_.recipients_accountids_.Add(value);
}
inline void CMsgGCGiftedItems::add_recipients_accountids(uint32_t value) {
  _internal_add_recipients_accountids(value);
  // @@protoc_insertion_point(field_add:CMsgGCGiftedItems.recipients_accountids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
CMsgGCGiftedItems::_internal_recipients_accountids() const {
  return _impl_.recipients_accountids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
CMsgGCGiftedItems::recipients_accountids() const {
  // @@protoc_insertion_point(field_list:CMsgGCGiftedItems.recipients_accountids)
  return _internal_recipients_accountids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
CMsgGCGiftedItems::_internal_mutable_recipients_accountids() {
  return &_impl_.recipients_accountids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
CMsgGCGiftedItems::mutable_recipients_accountids() {
  // @@protoc_insertion_point(field_mutable_list:CMsgGCGiftedItems.recipients_accountids)
  return _internal_mutable_recipients_accountids();
}

// -------------------------------------------------------------------

// CMsgApplyAutograph

// optional uint64 autograph_item_id = 1;
inline bool CMsgApplyAutograph::_internal_has_autograph_item_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgApplyAutograph::has_autograph_item_id() const {
  return _internal_has_autograph_item_id();
}
inline void CMsgApplyAutograph::clear_autograph_item_id() {
  _impl_.autograph_item_id_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint64_t CMsgApplyAutograph::_internal_autograph_item_id() const {
  return _impl_.autograph_item_id_;
}
inline uint64_t CMsgApplyAutograph::autograph_item_id() const {
  // @@protoc_insertion_point(field_get:CMsgApplyAutograph.autograph_item_id)
  return _internal_autograph_item_id();
}
inline void CMsgApplyAutograph::_internal_set_autograph_item_id(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.autograph_item_id_ = value;
}
inline void CMsgApplyAutograph::set_autograph_item_id(uint64_t value) {
  _internal_set_autograph_item_id(value);
  // @@protoc_insertion_point(field_set:CMsgApplyAutograph.autograph_item_id)
}

// optional uint64 item_item_id = 2;
inline bool CMsgApplyAutograph::_internal_has_item_item_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgApplyAutograph::has_item_item_id() const {
  return _internal_has_item_item_id();
}
inline void CMsgApplyAutograph::clear_item_item_id() {
  _impl_.item_item_id_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint64_t CMsgApplyAutograph::_internal_item_item_id() const {
  return _impl_.item_item_id_;
}
inline uint64_t CMsgApplyAutograph::item_item_id() const {
  // @@protoc_insertion_point(field_get:CMsgApplyAutograph.item_item_id)
  return _internal_item_item_id();
}
inline void CMsgApplyAutograph::_internal_set_item_item_id(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.item_item_id_ = value;
}
inline void CMsgApplyAutograph::set_item_item_id(uint64_t value) {
  _internal_set_item_item_id(value);
  // @@protoc_insertion_point(field_set:CMsgApplyAutograph.item_item_id)
}

// -------------------------------------------------------------------

// CMsgGCUserTrackTimePlayedConsecutively

// optional uint32 state = 1;
inline bool CMsgGCUserTrackTimePlayedConsecutively::_internal_has_state() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgGCUserTrackTimePlayedConsecutively::has_state() const {
  return _internal_has_state();
}
inline void CMsgGCUserTrackTimePlayedConsecutively::clear_state() {
  _impl_.state_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t CMsgGCUserTrackTimePlayedConsecutively::_internal_state() const {
  return _impl_.state_;
}
inline uint32_t CMsgGCUserTrackTimePlayedConsecutively::state() const {
  // @@protoc_insertion_point(field_get:CMsgGCUserTrackTimePlayedConsecutively.state)
  return _internal_state();
}
inline void CMsgGCUserTrackTimePlayedConsecutively::_internal_set_state(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.state_ = value;
}
inline void CMsgGCUserTrackTimePlayedConsecutively::set_state(uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:CMsgGCUserTrackTimePlayedConsecutively.state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::EGCItemMsg> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EGCItemMsg>() {
  return ::EGCItemMsg_descriptor();
}
template <> struct is_proto_enum< ::EGCMsgResponse> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EGCMsgResponse>() {
  return ::EGCMsgResponse_descriptor();
}
template <> struct is_proto_enum< ::EUnlockStyle> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EUnlockStyle>() {
  return ::EUnlockStyle_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_econ_5fgcmessages_2eproto
